### ISSUE TITLE
Rest and spread for Source §3

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1049]
Source follows the need of SICP JS. SICP JS mentions rest and spread:

https://sourceacademy.nus.edu.sg/sicpjs/3.4.2#h4

Therefore Source §3 should include rest and spread syntax.

This feature would be crucial if we were to adapt
Software Design for Flexibility
https://mitpress.mit.edu/books/software-design-flexibility
to JavaScript

**Comment by openorclose** [comment]
Would this change have to be made for all the modes of execution?

I can handle the transpiler and interpreter

**Comment by martin-henz** [comment]
Great. Transpiler and interpreter are enough. It's Source §3, so we won't need the stepper.
