### ISSUE TITLE
Source §3 Concurrent: doesn't support rest and spread syntax

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1064]
Feature introduced in Source §3 in July 2021

**Comment by martin-henz** [comment]
It would be nice to make Source §3 Concurrent consistent with Source §3 with respect to the rest and spread syntax. Currently we get:

list(...[1,2,3]);
==> Error: Unsupported operation

function f(x,...y) {
    return y;
}
==> Line 2: Name y not declared.

**Comment by martin-henz** [comment]
Same as #1616

**Comment by RichDom2185** [comment]
Duplicate of #1616
