### ISSUE TITLE
Stepper: programs that end with a declaration don't show correct result

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1108]
<img width="976" alt="Screenshot 2021-08-26 at 5 45 26 PM" src="https://user-images.githubusercontent.com/30220768/130941361-00330a51-d25e-4bd5-96d8-2359b9e11146.png">

Correct result: undefined

<img width="976" alt="Screenshot 2021-08-26 at 5 46 00 PM" src="https://user-images.githubusercontent.com/30220768/130941401-730bf943-8e1d-4156-be51-7680ae81920c.png">

Correct result: undefined

**Comment by martin-henz** [comment]
The rules are given here: https://sourceacademy.org/sicpjs/4.1.2#p23

**Comment by parnikkapore** [comment]
(reopening this to wait for the implementation)
