### ISSUE TITLE
Stepper: stops at applying empty function body

### ISSUE THREAD

**Issue by Cloud7050** [source-academy/js-slang#1109]
![image](https://user-images.githubusercontent.com/44526554/130951925-80531d63-f087-4df4-8d92-4a5f87485651.png)

This program is able to run normally.

However, the stepper stops at trying to run `a()` where the function has an empty body, displaying an empty output message on the right:

![image](https://user-images.githubusercontent.com/44526554/130952115-e3fb90a2-66bd-43d3-a259-1db9eb71fee4.png)

The stepper also stops when using such a lambda:

![image](https://user-images.githubusercontent.com/44526554/130952355-cb1303bb-c39e-4807-b066-049d3bcc6296.png)

Explicitly returning `undefined` seems to let it proceed:

![image](https://user-images.githubusercontent.com/44526554/130955171-1e0be0d4-d7e0-42ba-aed4-7d7ee4fdf4a4.png)

However, this may be a thing different from #1108, despite that also depicting empty function bodies and `undefined`. Since it seems to be about the stepper understanding empty function bodies, rather than about the stepper displaying `undefined` when ending on some *declaration*. Eg, the function run (*application*?) here doesn't need to return `undefined` as well, it can do something else like return `1` and proceed, as long as its body is not empty:

![image](https://user-images.githubusercontent.com/44526554/130955413-27d4349b-4682-4671-90ae-c681c3f4ca3a.png)

The empty output message is reminiscent of how the stepper acts when a program actually encounters an error:

![image](https://user-images.githubusercontent.com/44526554/130953966-188778e5-ae64-42ad-bd66-1778c8d3df02.png)

Submitted with reference to my [Piazza post](https://piazza.com/class/krvh5l6ipib380?cid=115_f1). I'm not completely certain if this isn't just another effect stemming from #1108, where said issue spawned from [the same thread](https://piazza.com/class/krvh5l6ipib380?cid=115).

**Comment by parnikkapore** [comment]
At [the end of stepper.ts:apply()](https://github.com/source-academy/js-slang/blob/343bf1eec7e27b5749fad3f82ee9956908c39eef/src/stepper/stepper.ts#L1280), the first statement is assumed to exist, but in this case, the body is empty, so firstStatement becomes `undefined`

I tried patching the function to return `ast.identifier('undefined')` in this scenario instead, and evaluation successfully continues.

This patch does not resolve #1108, nor does it resolve #1111 (which is a `too much recursion` for both forms).
