### ISSUE TITLE
Stepper: stops at hidden nested lambdas

### ISSUE THREAD

**Issue by Cloud7050** [source-academy/js-slang#1111]
This code below is from Q1's description for the Quest on Functional Expressionism:

```js
const repeat = n => f => x => n === 0 
                              ? x 
                              : repeat(n - 1)(f)(f(x));
const thrice = repeat(3);
const warn = thrice(display);
warn("ALERT"); // Displays "ALERT" 3 times.
```

The program runs fine via the run button, but cannot be stepped through in the stepper:

![image](https://user-images.githubusercontent.com/44526554/131167408-1172656e-1ed2-4169-8568-02d21014f7ce.png)

It may be related to how the nested lambdas have gotten expressed as `...` (highlighted in the image). Though curiously, a different, more complex program worked with the stepper also expressing `...`:

![image](https://user-images.githubusercontent.com/44526554/131220258-35bf0b97-a6df-47ea-81e2-cff84258930f.png)

The empty output message is reminiscent of #1109 and when running a program that truly encounters errors.

**Comment by petermonky** [comment]
The issue can be recreated with:

```js
const x = () => x;
function f(g) {
    return 0;
}
f(x);
```

The REPL displays the result just fine:

<img alt="REPL result" src="https://user-images.githubusercontent.com/39848410/132517994-573d4a1f-dc82-429a-86f6-9f52cb19e124.png">

but the Stepper fails:

<img alt="Stepper result" src="https://user-images.githubusercontent.com/39848410/132518077-46fd9894-1e93-4407-9846-cb4fac154c8c.png">

**Comment by petermonky** [comment]
Possibly relevant issue reported on Piazza in [@238](https://piazza.com/class/krvh5l6ipib380?cid=238).

Can be recreated with:

```js
const f = () => f;
const g = () => f;
```

The REPL correctly displays `undefined`:

<img alt="REPL" src="https://user-images.githubusercontent.com/39848410/132989553-6b3031c2-cc75-4e89-b084-7c51903e82c9.png">

but the Stepper crashes:

<img alt="Stepper" src="https://user-images.githubusercontent.com/39848410/132989592-19302cd7-db2c-470b-90cc-78693dc28c9a.png">

**Comment by parnikkapore** [comment]
It looks like the stepper is substituting functions' names with their lambda expressions when a constant declaration of that function is executed! This does not happen with function declarations, [nor is it seem to be expected in the substitution model when recursion is involved.](https://sourceacademy.org/sicpjs/1.2.1)

...[The latter for good reason.](https://github.com/source-academy/js-slang/issues/1111#issuecomment-915276716)

**Comment by Ziwen510** [comment]
[#issue 1433](https://github.com/source-academy/js-slang/issues/1433) also solves this issue.

**Comment by hanscau** [comment]
Issue no longer persists on the current implementation of the stepper.
