### ISSUE TITLE
Accessing property on undefined fails silently

### ISSUE THREAD

**Issue by openorclose** [source-academy/js-slang#113]
`undefined["some key"]` fails silently. Should throw an error instead. Same goes for null.

**Comment by martin-henz** [comment]
This is critical. It can lead to the Academy going down unexpectedly, and students losing work etc.

Needs to be fixed before the Practical Assessment on Thursday.

**Comment by ningyuansg** [comment]
@openorclose I get `'null' literals are not allowed` for null.

```javascript
null;
```

@martin-henz I'm not sure how this can crash the website or cause students to lose work. The bug has to do with the source interpreter that we run in the browser for the students, and cannot have an effect on the AWS servers serving the website to the students, or on the backend servers/database which stores the data.

**Comment by martin-henz** [comment]
I see. Here is what Edric reported:

Eldric Liew, [9 Nov 2018 at 8:35:26 AM]:
https://piazza.com/class/jg1gbtzfzh816w?cid=777

Quite a number of students got stuck at a bug which halts source academy without error

in particular:

undefined["x"] = 1;
display("test");

**Comment by martin-henz** [comment]
So that's not accurate: "halt source academy without error", even not "halt source academy client tab without error"?

Hmm, "quite a number of students" got stuck, we should fix it.

**Comment by openorclose** [comment]
@ningyuansg, I meant if for some reason `null` is ever returned for some reason from a builtin function, it should not fail silently as well.

**Comment by martin-henz** [comment]
Yes, there should be an error, even if it says: "internal error: null value encountered". But if we can locate the error, for example to an array access, the error message could say: "attempt to apply arrray access to non-array value".

**Comment by thomastanck** [comment]
Resolved by #120. Good work!

Could someone help close this issue?
