### ISSUE TITLE
Env Visualizer error when last breakpoint is an appllication of lambda expression

### ISSUE THREAD

**Issue by Elben85** [source-academy/js-slang#1167]
In the environmental visualizer, if the last breakpoint is an application of a lambda expression with at least one argument, it will not create a new frame. For example, in the following screenshot, there are 2 calls to a lambda expression, but it only creates 1 new frame.
<img width="104" alt="Screenshot 2021-11-02 174713" src="https://user-images.githubusercontent.com/93040801/139824130-bb01e820-ce15-45be-801c-f686c173cbf0.png">

<img width="248" alt="Screenshot 2021-11-02 174728" src="https://user-images.githubusercontent.com/93040801/139824137-623280ec-e853-49d3-8aa6-6920ae5a88d1.png">
.

**Comment by martin-henz** [comment]
This is not a bug but a misunderstanding: The meaning of a "breakpoint" is to pause the program BEFORE the line is evaluated at which the breakpoint is set.
