### ISSUE TITLE
draw_data([]); crashes Source

### ISSUE THREAD

**Issue by teekaytai** [source-academy/js-slang#1181]
The rough train of thought leading up to this:
```
draw_data([1, 1]);  // returns [1, 1]
draw_data([1, 1], [2, 2]);  // returns [[1, 1], [2, 2]]
draw_data();  // returns []
draw_data([]);  // ??
```

**Comment by thomastanck** [comment]
Do you want to work on this?

**Comment by teekaytai** [comment]
I'll pass. Admittedly I don't really understand how draw_data works

**Comment by martin-henz** [comment]
This issue might be similar to this: https://github.com/source-academy/frontend/pull/1981
