### ISSUE TITLE
missing dependency in SICP package

### ISSUE THREAD

**Issue by shenyih0ng** [source-academy/js-slang#1192]
SICP package exposes all `builtIns` under `Source 4` which includes **`parse`**.

`parse` in turn has a dependency on the `validator` module, but it is excluded in the build process

https://github.com/source-academy/js-slang/blob/4005580cf4b62bffe922045260b47313a9f7f37e/scripts/build_sicp_package.sh#L26

This results in a `MODULE_NOT_FOUND` error during ["side-effect" import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#import_a_module_for_its_side_effects_only) (`import 'sicp'`) and calling `parse`

```
Error: Cannot find module '../validator/validator'
```

> By including `validator` in the build process resolves the error when tested locally

Was wondering if there is a reason for not including `validator` in the build?

**Comment by martin-henz** [comment]
@hungkhoaitay do you have a view on this?

**Comment by hungkhoaitay** [comment]
@shenyih0ng by that time, I just tried to minimize the number of dependencies to be included by testing one by one. 

According to you, I should include the `validator` into the SICP package, right?

**Comment by shenyih0ng** [comment]
> @shenyih0ng by that time, I just tried to minimize the number of dependencies to be included by testing one by one.
> 
> According to you, I should include the `validator` into the SICP package, right?

yes I believe so as the current version (`v1.0.25`) of sicp will throw a `MODULE_NOT_FOUND` when we try to call `parse`
