### ISSUE TITLE
Statement after return executed

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#124]
function f() {
    return (() => 1)();
    display("here");
}
f();

currently displays "here"

**Comment by blackening** [comment]
Specifically, a function call causes it to fail.
```
function f(x) { 
    display("return");
    return math_abs(x);
    display("post-return"); //Displays
    return x;
    display("post-post-return"); //Does not display
}

f(1);
```

**Comment by blackening** [comment]
Probable fix. Someone please go test.

https://github.com/source-academy/js-slang/blob/afba4502fb22e5c79c1e949eb554779be969d369/src/interpreter.ts#L503
```
result instanceof ReturnValue ||
result instanceof BreakValue ||
result instanceof ContinueValue 
|| result instanceof TailCallReturnValue //Missing
```
https://github.com/source-academy/js-slang/blob/afba4502fb22e5c79c1e949eb554779be969d369/src/interpreter.ts#L517

```
if(result instanceof ReturnValue
|| result instanceof TailCallReturnValue) //missing
```
