### ISSUE TITLE
Module functions' implementations not hidden when displayed

### ISSUE THREAD

**Issue by Cloud7050** [source-academy/js-slang#1242]
Native Source functions have their internals displayed as `[implementation hidden]` when they get passed into `display()`, however, this hiding does not happen for imported module functions.

**Comment by martin-henz** [comment]
Not sure what the behavior SHOULD be. At the moment, we don't have a connection from the declaration in import to the module documentation yet. We have such a connection, using command-b, for the predeclared functions. So the display might be currently convenient to get a quick idea of what the function does. Any views on this?

**Comment by Cloud7050** [comment]
The displayed module function implementations are the transpiled and minified TypeScript code fetched from the modules API. Therefore, the displayed code can be rather messy:

![image](https://user-images.githubusercontent.com/44526554/162368873-ba11a6ef-5f2b-410a-996c-994c88121cb1.png)

As opposed to the hidden implementations of pre-defined functions:

![image](https://user-images.githubusercontent.com/44526554/162368898-92f6f59e-b923-41e3-a4eb-b835836748f1.png)

The ideal scenario would be having in-context documentation suggestions show up for module functions just like for the pre-declared functions, eliminating the use case of displaying module functions for a quick peek:

![image](https://user-images.githubusercontent.com/44526554/162369558-f27f1b38-1eb6-4c5d-b94e-789a004c7393.png)

But until then, it may be more helpful to simply have the proper module documentation open for reference (ie hide module function implementations outright):

![image](https://user-images.githubusercontent.com/44526554/162368961-de9c4758-d00c-4136-a306-edae96b1c120.png)
