### ISSUE TITLE
Migration to `renovate` as dependency management tool

### ISSUE THREAD

**Issue by shenyih0ng** [source-academy/js-slang#1260]
[Renovate](https://docs.renovatebot.com/) offers much more control and features as compared to current dependabot.

**It is able to group multiple dep upgrades into 1 PR.** (enuf said)

Markplace: https://github.com/marketplace/renovate

**Comment by martin-henz** [comment]
@shenyih0ng  can you bring this up in the steering committee. It seems to be something that the whole Source Academy can benefit from. Tx.
