### ISSUE TITLE
yarn build does not build the dist directory

### ISSUE THREAD

**Issue by johnbendi** [source-academy/js-slang#1264]
After I deleted the dist directory manually, running `yarn build` does not build the dist directory again. The README is also not clear on what to do.

**Comment by shenyih0ng** [comment]
Hi @johnbendi, thanks for flagging this out. A possible workaround is to first delete the `tsconfig.tsbuildinfo` file that was generated in the initial build process and run the same `yarn build` command again. This should generate the `dist` directory. Let me know if this works for you!

**Comment by johnbendi** [comment]
Hello @shenyih0ng, thanks for the reply. I can't find a `tsconfig.tsbuildinfo` in the root of the project or in the `dist` directory. I was only able to rebuild the dist directory by temporarily deleting the `incremental` option in `tsconfig.json` and putting it back after the `dist` directory was regenerated. What's the location for the `tsconfig.tsbuildinfo`?

**Comment by shenyih0ng** [comment]
> Hello @shenyih0ng, thanks for the reply. I can't find a `tsconfig.tsbuildinfo` in the root of the project or in the `dist` directory. I was only able to rebuild the dist directory by temporarily deleting the `incremental` option in `tsconfig.json` and putting it back after the `dist` directory was regenerated. What's the location for the `tsconfig.tsbuildinfo`?

It should be under the home directory. The way you did it is also a viable workaround! I think we could update the instructions a little bit and improve the `build` command as well. Will ref the PR here!
