### ISSUE TITLE
Make js-slang work with readline history

### ISSUE THREAD

**Issue by johnbendi** [source-academy/js-slang#1265]
I noticed that js-slang does not support `readline history` via `rlwrap` specifically. I'm yet to test with any other readline history library. Is it possible to make js-slang support readline history?

**Comment by johnbendi** [comment]
I'm currently able to work around this limitation by using the `-a` option to `rlwrap`

**Comment by martin-henz** [comment]
Issue doesn't seem to be important. @johnbendi have you managed to try other readline tools? If you need js-slang to work with rlwrap, you may want to check what error occurs and see how to fix it.
