### ISSUE TITLE
Autograder gives [RUNTIME] Line 0: Error(s) occurred when executing the module "Rune".

### ISSUE THREAD

**Issue by ThatGirlJam** [source-academy/js-slang#1282]
For Path : Runology assignment Q4 and 5, there is an issue with the predeclared module RUNE when Autograder marks assignment.

Although test cases are passed, Autograder has the error :

[RUNTIME] Line 0: Error(s) occurred when executing the module "Rune".

Attached are screen grabs after running the programs. 
<img width="1406" alt="Screenshot 2022-08-12 at 3 25 12 PM" src="https://user-images.githubusercontent.com/98588669/184306382-4ff3a828-65f8-4101-be33-2300131ca0a3.png">
<img width="1398" alt="Screenshot 2022-08-12 at 3 25 59 PM" src="https://user-images.githubusercontent.com/98588669/184306514-3858f139-f92e-40f1-9b14-0c56c75f1a73.png">

**Comment by YaleChen299** [comment]
Thanks for your report! This issue is not a js-slang issue but our autograder version issue. 
It is fixed now so I will close this.

**Comment by ThatGirlJam** [comment]
I see, so sorry for posting on the wrong thread, I'm not too familiar with
the system. Thank you very much for your help!
