### ISSUE TITLE
LANG: Eliminate js-slang hangs

### ISSUE THREAD

**Issue by thomastanck** [source-academy/js-slang#132]
Occasionally js-slang will hang and you can't do anything.

This is not supposed to happen! The interpreter is written purely with generators and the `scheduler` slowly steps through the evaluation generator, so the main thread only ever evaluates in small bits before returning control to the UI.

Had a hunch that builtins was causing the issue, and it was pretty much correct. Refer to my experiments below:

https://sourceacademy.nus.edu.sg/playground#chap=4&ext=NONE&prgrm=PTAEFpK6dv9gKBKAKgCQJIDkDiBlNdAQVVABFMBRRZMAMwFcA7AYwBcBLAe2dHoAUADwDOASlABvOqFmyATgFN2jeX0EBbAIYAHYQF4AfEIDUARgA0unYuYATYSIuhRYtwG4ZAXxmCANpwi7AJmHrRMbFy8-MIS0nKgSipqMUJinj7aevTOAUEhYTIIxSWlMhg4BESkoCR4oADSOOTEtCgRHDzqAnEyCQDuABacfooC7PKMir0oCQmC6X1yPigrDD2eviyd0QtSS7ILnqu%2BG21gpZdXUOVYeIQYNeQA8tgA5GSUNFuRXTEzYASSVU3UWJ3aZx%2BO1B%2B1mciGI0UoHGk2msMBy28p0WMgRo2REymANAPihURh0nBYDxSJRRPRcyO3iAA

To resolve this we would probably need to rewrite all the builtins in a generator style fashion such that evaluation can be stepped through. An alternative is to allow builtins to be written synchronously but allow the the evaluation generators of source functions to "pass through" the builtin. (see the uncommented experiment)

**Comment by angelsl** [comment]
What if evaluation was offloaded to a web worker instead? It's also probably more efficient not to have to return to the UI every now and then.

**Comment by martin-henz** [comment]
We can apply the same time-out mechanism that @openorclose is using for NATIVE.

**Comment by martin-henz** [comment]
Seems all fixed. @thomastanck can you check?

**Comment by thomastanck** [comment]
Not at all. Almost all buggy snippets from before still hang.

Just a random example I tried:

```
const y = map(x=>map(x=>x, enum_list(1,1000)), enum_list(1,1000));
```
https://sourceacademy.nus.edu.sg/playground#chap=3&exec=1000&ext=NONE&prgrm=MYewdgzgLgBAnjAvDAtgQwA4AoAeiB862e%2BOANDAKZgCuKA%2BgDYCW0WAjGewAy8CUfCtTpNWUDl17cBAbiA

**Comment by martin-henz** [comment]
For this example

`const y = map(x=>map(x=>x, enum_list(1,1000)), enum_list(1,1000));
`
I'm getting

`Line -1: RangeError: Maximum call stack size exceeded`

A bit awkward, but better than crashing. I'm using Chrome Version 77.0 on Mac OS 10.14.

**Comment by thomastanck** [comment]
Try this instead

const y = map(x=>map(x=>map(x=>x, enum_list(1,100)), enum_list(1,100)), enum_list(1,100));

**Comment by martin-henz** [comment]
For this example

```const y = map(x=>map(x=>map(x=>x, 
               enum_list(1,100)), enum_list(1,100)), enum_list(1,100));```

I get the following error message:

```Line 33: Potential infinite recursion detected: pair([ [ 1,
  [ 2,
  [ 3,
  [ 4,
  [ 5,
  [ 6,
  [ 7,
  [ 8,
...```

The error message is very long, and printing it takes a while. This seems to be the source of the problem: We need to truncate the display of values in such error messages, and limit it to a certain depth.

**Comment by martin-henz** [comment]
Considering this, can we say that this Issue is subsumed by https://github.com/source-academy/js-slang/issues/311 ?

Are there examples that cannot be attributed to very large value displays in the REPL?

**Comment by thomastanck** [comment]
Seems not. When playing, the hangs I got hanged for time proportional to the error message length, so it seems you've got a better grasp of the problem :3

**Comment by thomastanck** [comment]
Nope, I take that back, seems like the classic `fib` dies

```
function fib(n) {
    return n < 2 ? n : fib(n-1) + fib(n-2);
}
fib(34); // appropriate number here
```

https://sourceacademy.nus.edu.sg/playground#chap=3&exec=1000&ext=NONE&prgrm=GYVwdgxgLglg9mABMGAjAFGAlIg3gKESMQCcBTKEEpJAHkQCZEB%2BRJALmTUwFoBGHAGouGMDwZYA3PgC%2B%2BFBgDMAFilA

I don't get any timeouts, the browser becomes unresponsive while it runs. Could you check on your browser as well?

![maim9986](https://user-images.githubusercontent.com/829070/67168753-c92af800-f3d9-11e9-9473-b6783036164b.png)

**Comment by thomastanck** [comment]
https://github.com/source-academy/js-slang/blob/b0a96ef21b1c6bc9abf3dad915bb8cc7bb81c8a8/src/utils/operators.ts#L146-L147

I looked through how we handle timeouts, and it seems we do a good job stopping actual infinite loops (for/while loop, tail recursion), but otherwise we still have the ability to run some exponential function on the stack, so while it will eventually terminate (due to "max stack size exceeded"), it will take a very long time and hang.

**Comment by thomastanck** [comment]
The fix seems simple. We can check the time after each recursive call rather than before each recursive call. This doesn't affect the performance since we will be performing exactly the same number of operations as before.

https://github.com/source-academy/js-slang/blob/b0a96ef21b1c6bc9abf3dad915bb8cc7bb81c8a8/src/utils/operators.ts#L166

@openorclose thoughts?
