### ISSUE TITLE
Update specs: Disallow programs where function declarations do not appear at the top of their block scope

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#136]
See #40

**Comment by openorclose** [comment]
Should we still keep this? 

https://github.com/source-academy/js-slang/pull/54#issuecomment-425703512

As per the discussion there and the suggestion by yyc, we would treat function declarations like let/const declarations, and only hoist the identifier up but not the definition.

So

```javascript
a();
function a() {
  return 1;
}
```
and 
```javascript
display(a);
const a = 1;
```
would result in both throwing the same error about a being not defined in Source.

This would continue to allow the following pattern, allowing function declarations anywhere before it is called:

```javascript
function step1() {
  return 1;
}
step1();
function step2() {
  return 2;
}
step2();

And we would not need this restriction anymore.

**Comment by martin-henz** [comment]
How about we simplify the specification (uniformly for global functions and local functions) as follows:

**Function declarations must precede the use of the declared name.**

This way, programs cannot make use of "hoisting" of function declarations.

(Previously, the specs said:
Function declarations within an outer function must precede all other statements in body of the outer function. )

I think this is also consistent with the current implementation, which does not complain in the following example (but would need to, according to the previous specs):

```function g() { 1; function f() { 2; } } g();```

**Comment by martin-henz** [comment]
Case closed?

**Comment by martin-henz** [comment]
How about changing the restriction as follows:

Functions must not be called before their corresponding function declaration is evaluated.

This way, peeps cannot make use of the "hoisting" of function declarations, and we don't need to detect the problem in our implementation. Programs where this rule is violated give proper error messages, indicating that the program does not belong to Source.

**Comment by martin-henz** [comment]
Case closed?

**Comment by thomastanck** [comment]
> Functions must not be called before their corresponding function declaration is evaluated.

I think that's good. It fits nicely with our current implementation and also plays well with JS.

**Comment by martin-henz** [comment]
handled by PR: 136 and 39
