### ISSUE TITLE
Use actual list/stream/etc libraries in the source spec docs

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#139]
- Source spec docs don't match up with what's being used in reality, so sometimes the code in the docs are wrong

**Comment by openorclose** [comment]
In this case, the difference is in syntax only. If we make sure all the other functions are the analogous TypeScript versions, would that be ok?

**Comment by martin-henz** [comment]
Not sure if I understand your comment, Daryl: Are you arguing for the inclusion of the TypeScript version in the doc? I think that's worth considering. (We could tell the students that it's written in TypeScript, a variant of JavaScript. The type annotations are clarifying the programs.)

**Comment by openorclose** [comment]
No, I meant that it's okay for the source docs and the actual implementation to be different, if the typescript merely adds types. It will be compiled to the same JavaScript anyway.

**Comment by martin-henz** [comment]
I compiled the Appendix an a rush and a few bugs snug in. By now, it's probably in good shape, with so many student eyeballs. But I think Thomas was suggesting a systematic way to handle this: If we just publish the **actual source**, we will never have such an issue again. I support this in principle: There would be (literally) a single source for the list and stream libraries.

**Comment by thomastanck** [comment]
When I suggested this I intended for the actual source to change and use the doc versions. If the library can be written in Source instead of built-ins it also becomes part of the tests implicitly

**Comment by martin-henz** [comment]
This Issue is handled by https://github.com/source-academy/js-slang/pull/245.
The goal is for the debugger (SUBST) to use the libraries.

**Comment by martin-henz** [comment]
https://github.com/source-academy/js-slang/pull/245
merged
