### ISSUE TITLE
Add support for local module import/export to Source Typed

### ISSUE THREAD

**Issue by zhaojj2209** [source-academy/js-slang#1401]
Currently, all import statements are treated as module imports in Source Typed, and there is no support for export syntax. Now that folder mode has been officially enabled, it would be good to add support for it to Source Typed as well.

Given that cyclic dependencies are not allowed in Source and types are preserved after evaluating programs in Source Typed, it may be sufficient to simply expand the type error checker to add support for export syntax, differentiate module imports and file imports, and typecheck the files in post-order traversal order.

**Comment by martin-henz** [comment]
Resolved by #1686, except #1693
