### ISSUE TITLE
Scheme: numbers not distinguishable from strings

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1407]
<img width="699" alt="Screen Shot 2023-04-15 at 3 22 37 PM" src="https://user-images.githubusercontent.com/30220768/232195449-dd81b650-601e-4c26-ad03-3c389a9708f1.png">

**Comment by s-kybound** [comment]
Apologies - this is due to an oversight in the current implementation of the `display` for the scheme languages, which will always output a string at the moment. Otherwise, the language can properly distinguish between different types of data. I'll get to fixing it soon.
