### ISSUE TITLE
Scheme: scoping issues

### ISSUE THREAD

**Issue by s-kybound** [source-academy/js-slang#1408]
The SICP MCE at its original, unchanged state will not work for the current Scheme implementation.

See the original MCE here: (https://share.sourceacademy.org/schememce1)

There is 1 immediate reason the code does not work - the scheme-cxr library is not part of the builtins for scheme. This can be rectified quickly. 

However, despite adding the required cxr procedures, the MCE continues to fail to work.

This is due to a double usage of the procedure `apply` in the same scope - the assignment of `apply` to the procedure `apply-in-underlying-scheme`, as well as the later definition of the MCE's custom `apply`. Due to JavaScript's scoping rules,  an error will be thrown indicating that `apply` cannot be used before initialization.

This, at the moment, is a major deviation from the expected behaviour of R7RS scheme that will be noted in scm-slang.

scm-slang could rectify this through the use of a "scope validator" - if 1. A value is defined or 2. A value is a builtin/prelude, and the value is redefined later, the latter definition can be transformed into a estree assignment operation instead of a variable definition. However, this would require a massive refactoring of the scm-slang parser (an intermediate scheme AST could help), and so this has to be relegated for a future version of scm-slang instead.

A quick fix to the MCE was attempted here: (https://share.sourceacademy.org/schememce2)

However, the code continues to fail! 

This is due to the fact that all builtins are currently treated as constants. A special case could be made for the Scheme variants in js-slang, where builtins could use `let` instead of `const`.

Unfortunately, the current best way to get the MCE to work is through renaming the MCE's `apply` to `apply-in-MCE`,
which I have done in this final version of the MCE: (https://share.sourceacademy.org/workingschememce)

**Comment by martin-henz** [comment]
A couple of thoughts on this:
* The top-level "define" in Scheme implementations makes desctructive changes in the toplevel environment. This allows Scheme programmers to incrementally change programs and make sure that function calls refer to the latest "define"d version of the function. We could aim for this kind of "define" in our Scheme version.
* Is "apply" part of the Scheme specs? If yes, we could deviate from the Scheme specs and rename "apply" to "apply-in-underlying-scheme".
