### ISSUE TITLE
Trailing spaces on blank lines results in error

### ISSUE THREAD

**Issue by RichDom2185** [source-academy/js-slang#1412]
When running Python 1, Having trailing spaces on otherwise blank lines results in errors:

* When number of spaces is a multiple of 4: `GenericUnexpectedSyntaxError`
* Otherwise, `NonFourIndentError`

Example:

```python
print("hi")
        
print("world")
```

Not sure if this should belong in frontend or here, or if this is intentional.

**Comment by Fidget-Spinner** [comment]
Could you transfer this issue to https://github.com/source-academy/py-slang/issues please?

The parser/tokeniser is really rough right now and needs a lot of work :). So I expect people to find a ton of bugs.

**Comment by RichDom2185** [comment]
I've transferred this issue to https://github.com/source-academy/py-slang/issues/5 and will be closing this one, thanks!
