### ISSUE TITLE
Source X Native: Some functions are not available

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1429]
<img width="969" alt="Screen Shot 2023-06-23 at 7 12 51 PM" src="https://github.com/source-academy/js-slang/assets/30220768/f371bf8a-40c9-41f8-8008-e4c411bb8ba3">

where X is 2-4. (Source 1 Native shouldn't have reverse)

**Comment by RichDom2185** [comment]
Not just `reverse`, but the following lists all functions that are not available in our Native Source variants:

* `accumulate`
* `append`
* `build_list`
* `enum_list`
* `equal`
* `filter`
* `for_each`
* `length`
* `list_ref`
* `list_to_string`
* `map`
* `member`
* `remove`
* `remove_all`
* `reverse`

**Comment by RichDom2185** [comment]
The following tested using Source 4 Native:

<table>
  <thead>
    <tr>
      <td>Available</td>
      <td>Unavailable</td>
    </tr>
  </thead>
  <tbody>
    <tr>
<td>

* `apply_in_underlying_javascript`
* `arity`
* `array_length`
* `char_at`
* `display`
* `display_list`
* `draw_data`
* `error`
* `get_time`
* `head`
* `Infinity`
* `is_array`
* `is_boolean`
* `is_function`
* `is_list`
* `is_null`
* `is_number`
* `is_pair`
* `is_string`
* `is_undefined`
* `list`
* `math_abs`
* `math_acos`
* `math_acosh`
* `math_asin`
* `math_asinh`
* `math_atan`
* `math_atan2`
* `math_atanh`
* `math_cbrt`
* `math_ceil`
* `math_clz32`
* `math_cos`
* `math_cosh`
* `math_E`
* `math_exp`
* `math_expm1`
* `math_floor`
* `math_fround`
* `math_hypot`
* `math_imul`
* `math_LN2`
* `math_LN10`
* `math_log`
* `math_log1p`
* `math_log2`
* `math_LOG2E`
* `math_log10`
* `math_LOG10E`
* `math_max`
* `math_min`
* `math_PI`
* `math_pow`
* `math_random`
* `math_round`
* `math_sign`
* `math_sin`
* `math_sinh`
* `math_sqrt`
* `math_SQRT1_2`
* `math_SQRT2`
* `math_tan`
* `math_tanh`
* `math_trunc`
* `NaN`
* `pair`
* `parse`
* `parse_int`
* `prompt`
* `set_head`
* `set_tail`
* `stream`
* `stream_tail`
* `stringify`
* `tail`
* `tokenize`
* `undefined`

</td>
<td>

* `__access_export__`
* `__access_named_export__`
* `accumulate`
* `append`
* `build_list`
* `build_stream`
* `enum_list`
* `enum_stream`
* `equal`
* `eval_stream`
* `filter`
* `for_each`
* `integers_from`
* `is_stream`
* `length`
* `list_ref`
* `list_to_stream`
* `list_to_string`
* `map`
* `member`
* `remove`
* `remove_all`
* `reverse`
* `stream_append`
* `stream_filter`
* `stream_for_each`
* `stream_length`
* `stream_map`
* `stream_member`
* `stream_ref`
* `stream_remove`
* `stream_remove_all`
* `stream_reverse`
* `stream_to_list`

</td>
    </tr>
  </tbody>
</table>
