### ISSUE TITLE
Env Viz: Program environment does not reflect values that are imported from modules

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1434]
<img width="1383" alt="Screen Shot 2023-07-05 at 3 58 50 PM" src="https://github.com/source-academy/js-slang/assets/30220768/631184fc-311e-4d67-9a0a-663e97221dc7">

Here the program environment should reflect the names show, heart, and stack, in addition to stack_them.

The name “stack” should be allocated in the program environment. Currently, the function “stack_them” magically knows how to apply the imported “stack” function, which is not good.

**Comment by martin-henz** [comment]
js-slang/src/ec-evaluator/interpreter.ts at master · source-academy/js-slang
Implementations of the Source languages, which are small sublanguages of JavaScript designed for SICP JS - js-slang/src/ec-evaluator/interpreter.ts at master · source-academy/js-slang

Looking at https://github.com/source-academy/js-slang/blob/master/src/ec-evaluator/interpreter.ts

it seems to me that the call of evaluateImports should be moved from evaluate (98) to (281) where the program environment gets created.

**Comment by tsinyee** [comment]
> js-slang/src/ec-evaluator/interpreter.ts at master · source-academy/js-slang Implementations of the Source languages, which are small sublanguages of JavaScript designed for SICP JS - js-slang/src/ec-evaluator/interpreter.ts at master · source-academy/js-slang
> 
> Looking at https://github.com/source-academy/js-slang/blob/master/src/ec-evaluator/interpreter.ts
> 
> it seems to me that the call of evaluateImports should be moved from evaluate (98) to (281) where the program environment gets created.

if we move the call to the function in line 281, what about the nonImportNodes returned by `evaluateImports` ? they should still be added to the agenda in `evaluate` (98)?

**Comment by leeyi45** [comment]
While we're here, perhaps we should look at making similar modifications to the interpreter?

**Comment by martin-henz** [comment]
> While we're here, perhaps we should look at making similar modifications to the interpreter?

By "interpreter" you mean: https://github.com/source-academy/js-slang/tree/master/src/interpreter/interpreter.ts, right?
I lost tack of where this interpreter is used? Is it legacy? The sister runtime in
https://github.com/source-academy/js-slang/tree/master/src/interpreter/interpreter-non-det.ts
is used in the variant Source §3 Non-Det. I suppose your comment applies also to interpreter-non-det.ts: It should be updated accordingly, once we have figured out what to do.

**Comment by martin-henz** [comment]
> > js-slang/src/ec-evaluator/interpreter.ts at master · source-academy/js-slang Implementations of the Source languages, which are small sublanguages of JavaScript designed for SICP JS - js-slang/src/ec-evaluator/interpreter.ts at master · source-academy/js-slang
> > Looking at https://github.com/source-academy/js-slang/blob/master/src/ec-evaluator/interpreter.ts
> > it seems to me that the call of evaluateImports should be moved from evaluate (98) to (281) where the program environment gets created.
> 
> yep that makes sense. but if we move the call to the function in line 281, what about the nonImportNodes returned by `evaluateImports` ? they should still be added to the agenda in `evaluate` (98)?

I think you can let the Program-code (line 281) take care of the nonImportNodes: Line 98 can create the Program instruction (that includes all module imports) and the Program-code can then deal with the module imports, and create the correct program environment, consisting of the names imported from modules and the names that are declared using const, let, and function.
