### ISSUE TITLE
Env Viz: Avoid unnecessary markers

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1441]
If the body of a function consists of a single return instruction, there is no need to place a marker. Example:

<img width="1029" alt="Screen Shot 2023-06-28 at 10 11 46 PM" src="https://github.com/source-academy/frontend/assets/30220768/f62aba22-21f6-4c7c-a6d2-0da24e6f0678">

This is an open-ended issue: There are many other body shapes that don't require a marker:
* The body is a sequence whose only return statement comes at the end.
* The body is a (possibly nested) conditional statement in all of whose branches the only return statement comes at the end.
* ...

**Comment by vansh284** [comment]
Closed as completed in https://github.com/source-academy/js-slang/pull/1454
