### ISSUE TITLE
Env Viz: Avoid unnecessary break markers

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1442]
Example:

<img width="1011" alt="Screen Shot 2023-07-13 at 3 58 38 PM" src="https://github.com/source-academy/frontend/assets/30220768/65737beb-5dd3-482c-95ba-b06feea10c7f">

We should check if the body of the loop has a break statement. If no, there is no need for the break marker. Similar for continue: If the body does not have a continue statement, there is no need for the continue marker.

**Comment by vansh284** [comment]
Closed as completed in https://github.com/source-academy/js-slang/pull/1454
