### ISSUE TITLE
Env Viz: cannot handle rest syntax

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1445]
https://share.sourceacademy.org/apy9e
```
function test(...params){
    display(params);
}
test(1,2);
```
when run in Env Viz, gives error in home tab:
```
Line 2: Name params not declared.
```
(The program runs properly when run in home tab.)

**Comment by vansh284** [comment]
Closed as completed in https://github.com/source-academy/frontend/pull/2579
