### ISSUE TITLE
Repeated parameters: forbidden in strict-mode-JS, allowed in Source?

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#146]
The current playground allows

```
function f(x, x) { 
    1;
}
```

I think this should be forbidden, as in strict-mode-JS.

**Comment by openorclose** [comment]
Turns out that this was a bug in our version of acorn, it's been fixed in 6.0.4 or earlier:

https://astexplorer.net/#/gist/c9f34bdf2b40fad900cf606e0a5fbc18/1741a1b94455ff87c2db462917bf58c8953d5843

**Comment by thomastanck** [comment]
Let's add one test case and bump the version then.
