### ISSUE TITLE
CSE Machine: Modify navigation arrows to jump to the previous or next change in environment diagram

### ISSUE THREAD

**Issue by wpinrui** [source-academy/js-slang#1496]
Currently, the navigation arrows on the CSE machine allow the user to jump back and forth between control instructions. When the user is trying to visualize the program without the control and stash, this is not a good experience because it typically takes several clicks to move on to the next statement evaluation or change in environment diagram. 

I propose a **jump to next** and **jump to previous** button as an enhancement that skips to the next or previous time that either the highlighted line in the program changed, or the environment diagram itself changed.

**Comment by martin-henz** [comment]
Good idea!

**Comment by martin-henz** [comment]
I don't think we need new buttons for this. When display of control and stash is turned off, the arrows > and < should just skip to the next or previous environment state.
