### ISSUE TITLE
CSE Machine: in nullary functions, env resets are effectively skipped

### ISSUE THREAD

**Issue by parnikkapore** [source-academy/js-slang#1501]
Initially reported at https://edstem.org/us/courses/42391/discussion/3688626

# Reproduction instructions

Run the following program with Source 3 in the CSE machine.

```js
let x = 1;

const g = () => 1;

function f() {
    function g() {
        return 2;
    }
    return(g());
}

f() + (a => a + 1)(3) + g();
```

Note that `a => a+1` is parented to the `f()` block env instead of the program env.

## Minimal example

```js
function f() {
    const a = 1;
    return 2;
}

f() + (a => a + 1)(3);
```

# Possible culprit

At step 31, we return from `f`. (contrary to the current-line pointer - eep!) As part of returning from the function, the current env should be changed to the program env.

However, as `return` swallows the `env` instruction on its way to `mark`, at step 33 we are already back on line 12... but with the current environment still in the `f` block frame.

As noted by the reporter, this issue does not manifest if `f` takes any arguments. This is because the `env` instruction corresponding to the `f` argument frame would *not* be swallowed, allowing the machine to return to the program env.

**Comment by martin-henz** [comment]
Possibly the same bug as this: https://github.com/source-academy/js-slang/issues/1493

**Comment by parnikkapore** [comment]
Likely fixed by https://github.com/source-academy/js-slang/pull/1494

**Comment by martin-henz** [comment]
Yes, fixed:
<img width="768" alt="Screenshot 2023-10-25 at 6 34 40 AM" src="https://github.com/source-academy/js-slang/assets/30220768/df6483a6-d354-4348-a3ed-f35f4349e568">
<img width="770" alt="Screenshot 2023-10-25 at 6 35 50 AM" src="https://github.com/source-academy/js-slang/assets/30220768/148f143c-f277-40ff-ba4f-350a0ff62a17">
