### ISSUE TITLE
Strict types for array and object access

### ISSUE THREAD

**Issue by thomastanck** [source-academy/js-slang#152]
I believe we should enforce strict types for array and object accesses. Object access should always be done with either `string`s or using the dot abbreviation. Array access should always be done using non-negative integers. What do you think @martin-henz?

If we want this then the following have to be done:

- [ ] New entries in the types table in source specs (/doc)
- [ ] RTTC should be added (checkMemberExpression)
- [ ] Call RTTC from interpreter.ts

**Comment by martin-henz** [comment]
Yes, sure. I agree. 

(note that objects go extinct)
