### ISSUE TITLE
CSE Machine: Redeclaring name bug

### ISSUE THREAD

**Issue by DiligentPenguinn** [source-academy/js-slang#1520]
While working on #1503 , I encountered a very weird bug
https://share.sourceacademy.nus.edu.sg/m9578
The result of the program should be undefined but instead it throws an error: "Redeclaring name b"

![Image](https://github.com/source-academy/js-slang/assets/128918146/c4eaff2d-95e6-4ead-87c5-a0a6e90ed212)

**Comment by NhatMinh0208** [comment]
[This](https://github.com/source-academy/js-slang/blob/d6553ca7499a0bb16593a9402c2cef724ba7fbc0/src/cse-machine/interpreter.ts#L828C1-L834C8) seems to be the culprit. The env instruction only gets pushed when there is a statement node in the control stack, which is not the case here.

**Comment by NhatMinh0208** [comment]
Also this issue is probably related to #1506

**Comment by NhatMinh0208** [comment]
#1506
