### ISSUE TITLE
Typed Source: Inconsistent typing of literals

### ISSUE THREAD

**Issue by RichDom2185** [source-academy/js-slang#1531]
<img width="1492" alt="image" src="https://github.com/source-academy/js-slang/assets/34370238/9e7aff2e-8315-4f7b-a7d5-4657341add24">

In line 3, the literal `1` is typed as `number`, but in line 4, the same literal `1` is typed as `1`.

**Comment by Zenkoh1** [comment]
Closed by PR https://github.com/source-academy/js-slang/pull/1556
