### ISSUE TITLE
CSE Machine: shows "name ... not declared" but does not flash "Introduction" (home) icon in red

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1552]
The CSE machine displays an error when a name is not declared. Example:
```
some_undeclared_name;
```
shows an error in REPL of "Introduction" tab: name undeclared_name not declared

However, the user is not guided to the introduction tab. This is a regression: We used to have a flashing red home icon in this case.

**Comment by RichDom2185** [comment]
I can't seem to reproduce this. It shows the error on https://sourceacademy.org/ when I try to run the problematic code.

**Comment by RichDom2185** [comment]
My bad, this is a regression in the frontend when we updated our UI library. I will fix this. Let me create a new frontend issue and close this one on js-slang.
