### ISSUE TITLE
Typed Source: Predeclared constants are also types

### ISSUE THREAD

**Issue by Zenkoh1** [source-academy/js-slang#1553]
<img width="960" alt="image" src="https://github.com/source-academy/js-slang/assets/76705864/61d9430f-c897-4ab9-8a36-062d27de779f">

In lines 1 and 2, the predeclared constants `NaN` and `math_PI` can be used as types without error. But those constants are values and it should not be possible to use them as types.

**Comment by martin-henz** [comment]
Small clarification:
_But those constants are values and it should not be possible to use them as types._

Actually, `NaN` and `math_PI` are predeclared names and not literals. Therefore they should not be allowed as types.
