### ISSUE TITLE
Stepper: does not get stuck when it should. Instead it crashes!

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1554]
The stepper should "get stuck" when builtins get called with the wrong argument types. Example:
```
math_sin(true); // crashes the stepper
```

<img width="886" alt="Screenshot 2024-02-20 at 5 46 06 PM" src="https://github.com/source-academy/js-slang/assets/30220768/10f422d7-19c4-4fd6-a02a-af208b975956">

**Comment by hanscau** [comment]
<img width="824" alt="image" src="https://github.com/source-academy/js-slang/assets/43413899/26e1294b-2260-45a3-af4a-2607b8ad6dea">

Surprisingly JS returns a value for this exact code

**Comment by RichDom2185** [comment]
> <img alt="image" width="824" src="https://private-user-images.githubusercontent.com/43413899/309490752-26e1294b-2260-45a3-af4a-2607b8ad6dea.png">
> Surprisingly JS returns a value for this exact code

Seems like `true` is being treated as `1`?

**Comment by hanscau** [comment]
Do we need to replicate that behaviour?

**Comment by martin-henz** [comment]
Not sure. Will check with the teaching team.
