### ISSUE TITLE
Stepper: ReferenceError is not shown, instead it get stuck

### ISSUE THREAD

**Issue by hanscau** [source-academy/js-slang#1587]
![image](https://github.com/source-academy/js-slang/assets/43413899/899e5b3d-f3d2-4585-94dd-1bb4fef553d7)

Stuck, instead it should show the error:

![image](https://github.com/source-academy/js-slang/assets/43413899/b96eef43-99db-430e-a17b-2f82748cd38f)

**Comment by martin-henz** [comment]
```
"cannot access 'x' before initialization
```
That's the correct error message for when the stepper wants to evaluate a name: Genuinely undeclared names are handled by the validator.

So basically, evaluation should get stuck, but the error should be displayed as above.
