### ISSUE TITLE
Stepper: Accidental unpacking during evaluating the if statement

### ISSUE THREAD

**Issue by FYL2003** [source-academy/js-slang#1588]
The unpacking of the block statement of the if statement may cause confusion.

The following figures is one of the examples.
<img width="1442" alt="Screenshot 2024-03-19 at 4 30 05 PM" src="https://github.com/source-academy/js-slang/assets/97390773/bbd0ebab-2916-46ac-a64c-a03d61330a01">
<img width="1441" alt="Screenshot 2024-03-19 at 4 30 21 PM" src="https://github.com/source-academy/js-slang/assets/97390773/629e1e8e-163c-46b1-85cc-b63f2e1e5a35">

**Comment by martin-henz** [comment]
Resolved
