### ISSUE TITLE
Strict types for +

### ISSUE THREAD

**Issue by thomastanck** [source-academy/js-slang#160]
# Proposal

- `+` should have the type signatures `(number, number) => number` and `(string, string) => string` only.
- expose `stringify` in chapter 1

# Motivation

`+` should enforce strict types: we should only allow `number` + `number` and `string` + `string`, as other combinations are considered bad practice.

Consider the following code
```
const a = 10;
const b = 20;
display('result is ' + a + b);
```

You would normally expect `result is 30` but here the number is added to string, so we actually get `result is 1020`.

If we enforce strict types, this would be a type error, prompting the student to use the following code instead:

```
const a = 10;
const b = 20;
display('result is ' + stringify(a + b));
```

which will result in `result is 30` as expected.

----

As a bonus, this also resolves some current Source-JS incongruities like
```
123 + list(4,5,6)
```
currently evaluating to `123[4, [5, [6, null]]]` in Source but `1234,5,6` in JS. The correct code
```
"123" + stringify(list(4,5,6))
```
would then evaluate to `123[4, [5, [6, null]]]` in both Source and JS.

----

What do you think, @martin-henz @openorclose?

**Comment by openorclose** [comment]
I think it's a good idea as well.
