### ISSUE TITLE
Undocumented behaviour: function expressions

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/js-slang#17]
The following is not specified in all source chapters, but passes evaluation by the interpreter:

```javascript
(function() { return 1; })();
```

**Comment by martin-henz** [comment]
Yes, indeed, this is undocumented behaviour. We should avoid it.

The rationale is to keep the language simple: One kind of function declaration statement, one kind of function definition expression. The latter is presented as a sort of abbreviation for the former.

**Comment by ningyuansg** [comment]
Note to devs that this probably only requires setting the value of the key for the node type for function expressions in syntaxTypes to the number infinity. Please try to add tests for it, though.

**Comment by thomastanck** [comment]
Closing in favour of #129, a combination of a bunch of issues, to clean up the list of issues a little.
