### ISSUE TITLE
Stepper: bug that causes frontend crash

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#1712]
https://share.sourceacademy.nus.edu.sg/z6al6

The program that crashes the frontend:

```
function a() {
    if (true) {
        display(1);
        return 1;
    } else {
        undefined;
    }
}
a();
```

**Comment by teleohead** [comment]
Another example that has caused clash, which we discussed this morning. @martin-henz 

It could be caused by any programmes involving the following error statement:

`tail(null);`

**Comment by teleohead** [comment]
I believe the frontend will crash as long as there is a type error of argument for `head()` and `tail()`.

Situation is the same with the following statements: (mainly wrong data types).

Ex.:

`tail();`
`tail(null);`
`tail(undefined);`
`head(undefined);`
`function foo() {}
head(foo);`
`head("foo");`

**Comment by teleohead** [comment]
believe the frontend will crash as long as there is a type error of argument for `head()` and `tail()`.

Situation is the same with the following statements: (mainly wrong data types).

Ex.:

`tail();`
`tail(null);`
`tail(undefined);`
`head(undefined);`
`function foo() {}

 head(foo);`
`head("foo");`

**Comment by teleohead** [comment]
I believe the frontend will crash as long as there is a type error of argument for `head()` and `tail()`.

Situation is the same with the following statements: (mainly wrong data types).

Ex.:

`tail();`
`tail(null);`
`tail(undefined);`
`head(undefined);`

```function foo() {}

 head(foo);```

`head("foo");`

**Comment by teleohead** [comment]
I believe the frontend will clash as long as there is a **TYPE ERROR** of argument for `head()` and `tail()`.

Situations are the same with the following statements:

`head();`
`tail("");`
`head(undefined);`
`function foo() {};  tail(foo);`
`head("foo");`

**Comment by martin-henz** [comment]
Got it. Thanks for the further details @teleohead
