### ISSUE TITLE
Libraries for using Source in Node.js and browsers

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#191]
The languages Source §x are proper sub-languages of JavaScript. In principle, this should allow our programs to run in native JavaScript environments such as browsers and Node.js. To live up to this potential, we should provide JavaScript libraries
source_1.js
source_2.js
source_3.js
source_4.js
We should put these on the server so that the users can include them like this:

<script src="https://sourceacademy.nus.edu.sg/scripts/source_3.js"></script>

**Comment by openorclose** [comment]
Some builtins like `display` and the list visualiser require some interaction with HTML to work. 

If we do not include them in the .js files, we would have to explain the difference between these .js files and the Source on the playground which would create confusion.

If we do include these in the .js files, then there would also need to be a basic HTML template that allows for these functions to work.

And then we would also have to consider allowing the importing of libraries like runes that also need extra HTML to work.
