### ISSUE TITLE
Builtins do not check argument length.

### ISSUE THREAD

**Issue by openorclose** [source-academy/js-slang#193]
In the interpreter, the built-in function itself checks (or doesn't check) whether or not the number of arguments is valid.

Should this be fixed?

If it should, we need to handle at least one special case of `list`, where it can take any number of arguments.

**Comment by thomastanck** [comment]
I think ideally we should check arguments if the # of arguments is fixed... but this means we need the builtin to tell us that the # of arguments was correct.

For simplicity we should probably have the builtin check the # of arguements themselves.
