### ISSUE TITLE
Undocumented in specifications: accessing index of array where index has not been set.

### ISSUE THREAD

**Issue by openorclose** [source-academy/js-slang#199]
For example, 

```javascript
const array = [];
a[0];
```

Currently it returns undefined, but is it better to throw an error instead?

**Comment by thomastanck** [comment]
I think it would be good to throw, it would make programs easier to debug.

**Comment by openorclose** [comment]
I think it'd be better to throw too. Need to check if missions or other materials use this "feature" before implementing it.

**Comment by martin-henz** [comment]
Yes, better throw.

**Comment by martin-henz** [comment]
Reminds me:

```
> const a = []; a[0] = 1; a[1] = undefined; a[3] = 1; a;
[ 1, undefined, <1 empty item>, 1 ]
```

Do we need the distinction between undefined and "empty item"?

**Comment by thomastanck** [comment]
Yes, but now it'll be easy to see/plainly obvious, since the problem before was that it wasn't throwing when trying to access the empty item, and would return `undefined`.

Now when teaching we merely have to run the code and show them that `a[1]` works but `a[2]` doesn't.

**Comment by martin-henz** [comment]
Hmm, I'm having second thoughts on this. The notion of something "not having a value" is mind-boggling. It's creeping up in the temporal dead zone discussion on the scope of const and let, and it's unavoidable there. But for arrays, do we need to complicate things? With our array primitives, we can just treat an array conceptually as a data structure that returns undefined for all but a finite number of values, which are the integers that have been explicitly assigned to values other than undefined.

To turn this comment into a question: Is there a way to distinguish "no value" from undefined, in the current Source implementation?

**Comment by martin-henz** [comment]
> Hmm, I'm having second thoughts on this. The notion of something "not having a value" is mind-boggling. It's creeping up in the temporal dead zone discussion on the scope of const and let, and it's unavoidable there. But for arrays, do we need to complicate things? With our array primitives, we can just treat an array conceptually as a data structure that returns undefined for all but a finite number of values, which are the integers that have been explicitly assigned to values other than undefined.
> 
> To turn this comment into a question: Is there a way to distinguish "no value" from undefined, in the current Source implementation?

So following this proposal, a debugging tool would be allowed (and encouraged) to show `undefined` as values in the gaps of arrays.

**Comment by martin-henz** [comment]
> > Hmm, I'm having second thoughts on this. The notion of something "not having a value" is mind-boggling. It's creeping up in the temporal dead zone discussion on the scope of const and let, and it's unavoidable there. But for arrays, do we need to complicate things? With our array primitives, we can just treat an array conceptually as a data structure that returns undefined for all but a finite number of values, which are the integers that have been explicitly assigned to values other than undefined.
> > To turn this comment into a question: Is there a way to distinguish "no value" from undefined, in the current Source implementation?
> 
> So following this proposal, a debugging tool would be allowed (and encouraged) to show `undefined` as values in the gaps of arrays.

This PR follows this line of argument: https://github.com/source-academy/js-slang/pull/280

**Comment by thomastanck** [comment]
I think this approach is good. If a student asks what "empty value" means we can tell them that for all practical purposes it just means undefined as per this definition, and tell them to look it up if they want to know the specifics.
