### ISSUE TITLE
RegExp Expressions are allowed

### ISSUE THREAD

**Issue by remo5000** [source-academy/js-slang#20]
![image](https://user-images.githubusercontent.com/12512488/42950033-bcf90fd8-8ba5-11e8-953f-34de7d44b03e.png)

😮

**Comment by ningyuansg** [comment]
lmao help

This probably needs to be stopped at rules. It's marked as an Literal in the AST with a property regex that other Literals don't have.

**Comment by remo5000** [comment]
Do we control expressions using Nodes?
