### ISSUE TITLE
Deviations from ECMAScript

### ISSUE THREAD

**Issue by openorclose** [source-academy/js-slang#225]
As we claim that _Source_ is a sublanguage of JavaScript, it is good to note down some of its deviations.

### Return value of a program
Executing
```js
1;
{
//empty block
}
```
,
- JavaScript returns `1`
- Source (interpreted) returns `undefined`
- Source (natively evaled) returns `undefined`

As it stands, it's looks like a really minor deviation, so it's not going to be fixed.

Objections are welcome.

**Comment by martin-henz** [comment]
OMG, JavaScript *is* weird. I have no idea what's going on!

```
{ }
{}
{;}
undefined
1; {};
1
{};
undefined
{}
{}
{1;};
1
```

**Comment by openorclose** [comment]
I believe you're running in the chrome console, so there's some minor differences. Try explicitly calling eval('code') on them and you'll see.

I think chrome tries to detect if what you type is exactly something in object notation, and then parses it as an object if possible. Any extra semicolons or any other characters cause it to parse it "properly", as  "{a:1}" should get parsed as a block statement with a label "a" and a statement "1" but does not in chrome. I tried this with firefox and "{a:1}" gets parsed properly and returns 1.


```js
//chrome weirdness
{ } //eval("{ }") returns undefined.
{} //empty object if run in chrome console, since it tries to parse as a single object.

{
;// empty statement, results in undefined
}
undefined //can't be parsed as a single object, so it's a block statement with one empty statement inside;


1; {};//not parsed as object, so this is an empty block};//empty statement
1 // last return value is 1;

{}//empty block;//empty statement, results in undefined
undefined

//chrome weirdness
{}//same as before, chrome parses this as a single object. eval("{}") would treat it as a blockstatement and return undefined;
{}

{1;};
1 //last evaluated statement


{a:1}; //can't be parsed as a single object, so it's parsed as a block statement with a label
1

//chrome weirdness
{a:1} //can be parsed as a single object so chrome does so.
{a: 1}
```

**Comment by martin-henz** [comment]
> I believe you're running in the chrome console, so there's some minor differences. Try explicitly calling eval('code') on them and you'll see.
> 
> I think chrome tries to detect if what you type is exactly something in object notation, and then parses it as an object if possible. Any extra semicolons or any other characters cause it to parse it "properly", as "{a:1}" should get parsed as a block statement with a label "a" and a statement "1" but does not in chrome. I tried this with firefox and "{a:1}" gets parsed properly and returns 1.
> 
> ```js
> //chrome weirdness
> { } //eval("{ }") returns undefined.
> {} //empty object if run in chrome console, since it tries to parse as a single object.
> 
> {
> ;// empty statement, results in undefined
> }
> undefined //can't be parsed as a single object, so it's a block statement with one empty statement inside;
> 
> 
> 1; {};//not parsed as object, so this is an empty block followed by empty statement
> 1 // last return value is 1;
> 
> {}//empty block
> ;//empty statement, results in undefined. not parsed as empty object due to extra semicolon
> undefined
> 
> //chrome weirdness
> {}//same as before, chrome parses this as a single object. eval("{}") would treat it as a blockstatement and return undefined;
> {}
> 
> {1;};
> 1 //last evaluated statement
> 
> 
> {a:1}; //can't be parsed as a single object, so it's parsed as a block statement with a label
> 1
> 
> //chrome weirdness
> {a:1} //can be parsed as a single object so chrome does so.
> {a: 1}
> ```

Oh boy, weirdness over weirdness!

**Comment by martin-henz** [comment]
> As we claim that _Source_ is a sublanguage of JavaScript, it is good to note down some of its deviations.
> 
> ### Return value of a program
> Executing
> 
> ```js
> 1;
> {
> //empty block
> }
> ```
> 
> ,
> 
> * JavaScript returns `1`
> * Source (interpreted) returns `undefined`
> * Source (natively evaled) returns `undefined`
> 
> As it stands, it's looks like a really minor deviation, so it's not going to be fixed.
> 
> Objections are welcome.

**no** objection!
