### ISSUE TITLE
Metacircular interpreter's parser uses AY17/18 Source Lanugage specs 

### ISSUE THREAD

**Issue by remo5000** [source-academy/js-slang#24]
### Problem
- The parser that is generated using `jison` uses grammar that works for the previous implementation for Source
- The rules would have to be changed
  - [ ] `var` must be changed to `const` and `let`
  - [ ] Arrow functions must be added
  - [ ] Anonymous functions must be removed (?)

**Comment by ningyuansg** [comment]
Note to future devs please use functions from the actual js-slang interpreter rather than defining a separate function with separate rules (i.e. rewrite parse to use js-slang functions).

**Comment by martin-henz** [comment]
This is important for Sem 1 2019/20, not for Sem 2 2018/19.
