### ISSUE TITLE
Error message when redeclaring constant

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#25]
In REPL, we currently have:
const a = 1;
undefined
const a = 2;
Line 1: Redeclaring variable a

Can we instead please have

Line 1: Redeclaring name a

The background: We try to avoid the term "variable" in Chapters 1 and 2. Instead, we use the term "name", or "constant".

**Comment by ningyuansg** [comment]
Opened #26 for this. Will take some time for it to show up in the web playground though, since we'll need to publish a new version of `js-slang` with this change, and then specify frontend to use that new version. Nonetheless, it'll be up by week 1's lecture.

**Comment by martin-henz** [comment]
Noted.
