### ISSUE TITLE
LANG: Names of predeclared library functions bound to undefined

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#255]
even when the library is not loaded.

Example:

sine_sound;

This will trip up students who forget to load the relevant library.

**Comment by martin-henz** [comment]
To be more precise, the Source Academy should pre-declare only those names that are documented in the Source §x specs and in the Source Library specs. Example: None of these variables should be declared here:

<img width="218" alt="Screenshot 2019-07-07 at 2 39 58 PM" src="https://user-images.githubusercontent.com/30220768/60764970-a17f8080-a0c5-11e9-83dd-fff14aa629e7.png">

**Comment by openorclose** [comment]
fixed by #308
