### ISSUE TITLE
INSPECT: Once debugger breakpoints are toggled, code always runs in interpreter mode

### ISSUE THREAD

**Issue by openorclose** [source-academy/js-slang#277]
Steps to reproduce:

https://sourceacademy.nus.edu.sg/playground

Running `while (true){}` should hang the browser for 1s.

Now click the line number to toggle a breakpoint, then toggle it again to turn it off.

Click run again, and the same code will now not hang the browser, and instead allow you to stop it,

**Comment by martin-henz** [comment]
This is fixed, right @podocarp  ?

**Comment by martin-henz** [comment]
closing this: it's fixed
