### ISSUE TITLE
Cannot redeclare undefined function

### ISSUE THREAD

**Issue by geshuming** [source-academy/js-slang#283]
Given the below code snippet,
```javascript
function map(f, xs) {
    return xs;
}

display(map);

map(x => x + 1 , list(1));
```

On Source 2 and above, the below output is received
```
function map(f, xs) {
  return xs;
}
[1, null]
```

On Source 1, the below output is received
```
function map(f, xs) {
  return xs;
}

Line 7: Calling non-function value undefined.
```

**Comment by openorclose** [comment]
This is an unfortunate issue. `list` is not defined in Source 1, and native intiialises all global variables to undefined. (Try `window;` in the repl, it will return `undefined`). 

The correct error message should be `Name list undeclared`, which will be a future enhancement to native. You can try running it in the interpreter by using "enable verbose";, which will show the correct error message.

**Comment by martin-henz** [comment]
Same as https://github.com/source-academy/js-slang/issues/255
