### ISSUE TITLE
ACADEMY: A way to mark functions to hide implementation

### ISSUE THREAD

**Issue by geshuming** [source-academy/js-slang#284]
Given our migration to have prepend in the future. We would like to have some way to declare functions and have their implementation hidden.

For example, maybe i can declare in the prepend
```javascript 
function* foo(bar) {
  // some implementation
}
```

and i call `foo;` in my code, i should get
```
function foo(bar) {
  [implementation hidden]
}
```

**Comment by martin-henz** [comment]
You mean to annotate the function somehow, right? You don't mean to use the generator syntax function*, I guess?

Do we insist that the prepended programs are Source?

If not, we can write:

function foo(bar) {
   ...
}
foo["implementation_hidden"] = true;

If we only allow Source, we could write:

function foo(bar) {
   ...
}
f[0] = true; 

to achieve the same effect.

**Comment by martin-henz** [comment]
It doesn't feel right to hide the implementations from the users. We should change assessments to live with the fact that all implementations are visible, I feel.

Any comments, anyone?
