### ISSUE TITLE
DOC: Comments on CURVES documentation

### ISSUE THREAD

**Issue by chrisjwelly** [source-academy/js-slang#295]
Some comments on [CURVES documentation](https://sicp.comp.nus.edu.sg/source/CURVES/):
1. In the main page, I think we should provide more details on the curves library. As a CS1101S alumnus, I had a hazy memory on how to use the curves library and visiting this documentation did not really help at first. 
Some things we could include:
    - A more concrete definition on 'Point', 'Curve', 'Drawing', 'Curve Operator', etc
    - Example usage and demonstration
    - Perhaps past contest winning entries to demonstrate the possibilities?

    I don't think this is difficult to achieve. The mission 'Curve Introduction' has already most of the information, and we only need to carefully transfer the contents over. 
2. [`rotate_around_origin`](https://sicp.comp.nus.edu.sg/source/CURVES/global.html#rotate_around_origin) has the correct description of returning a unary curve operator and taking in theta as parameter. However, its heading says that it takes in a Curve and returns a Curve. The earlier 'this function returns a unary Curve operator: ' in the description also seems redundant, because it is mentioned again slightly later in the sentence.
3. [`show_connected_gosper`](https://sicp.comp.nus.edu.sg/source/CURVES/global.html#show_connected_gosper) is said to return `curve_operator` in its heading. I tested this function and I think it returns a Drawing, which is correctly described in the description. I.e. Calling this function is sufficient to print the drawing in the REPL without prepending any `draw_...` function
4. [`gosper_curve`](https://sicp.comp.nus.edu.sg/source/CURVES/global.html#gosper_curve) is said to return `curve_operator` in the heading as well. I think it returns a Curve instead of a curve operator, which is also correctly described in the description. I.e. `draw_connected(20)(gosper_curve(4));` will print the Drawing in the REPL
5. I tested the library with [this version](https://github.com/source-academy/cadet-frontend/tree/25946d4c7045d28db8ed0353dc94c8ce837f5265) of cadet-frontend. The issues I had were mostly with some mistakes in the documentation mentioned above. I tried doing the missions 'Curve Introduction' and 'Curve Manipulation', and the pre-declared names are working well for these 2 missions at least. 
Edit: I forgot that 'Gosperize and Diagnostics' as well as 'Diagnostics and Dragonize' are curve missions too. Will try them out as soon as I can

I will play around more and report any bugs in the libraries if I spot them!

**Comment by martin-henz** [comment]
> Some comments on [CURVES documentation](https://sicp.comp.nus.edu.sg/source/CURVES/):
> 
> 1. In the main page, I think we should provide more details on the curves library. As a CS1101S alumnus, I had a hazy memory on how to use the curves library and visiting this documentation did not really help at first.
>    Some things we could include:
>    
>    * A more concrete definition on 'Point', 'Curve', 'Drawing', 'Curve Operator', etc
>    * Example usage and demonstration
>    * Perhaps past contest winning entries to demonstrate the possibilities?

Done, see https://github.com/source-academy/cadet-frontend/pull/719

>    
>    I don't think this is difficult to achieve. The mission 'Curve Introduction' has already most of the information, and we only need to carefully transfer the contents over.

Yes. see https://github.com/source-academy/cadet-frontend/pull/719

> 2. [`rotate_around_origin`](https://sicp.comp.nus.edu.sg/source/CURVES/global.html#rotate_around_origin) has the correct description of returning a unary curve operator and taking in theta as parameter. However, its heading says that it takes in a Curve and returns a Curve. The earlier 'this function returns a unary Curve operator: ' in the description also seems redundant, because it is mentioned again slightly later in the sentence.

Fixed in https://github.com/source-academy/cadet-frontend/pull/719

> 3. [`show_connected_gosper`](https://sicp.comp.nus.edu.sg/source/CURVES/global.html#show_connected_gosper) is said to return `curve_operator` in its heading. I tested this function and I think it returns a Drawing, which is correctly described in the description. I.e. Calling this function is sufficient to print the drawing in the REPL without prepending any `draw_...` function

Fixed in https://github.com/source-academy/cadet-frontend/pull/719

> 4. [`gosper_curve`](https://sicp.comp.nus.edu.sg/source/CURVES/global.html#gosper_curve) is said to return `curve_operator` in the heading as well. I think it returns a Curve instead of a curve operator, which is also correctly described in the description. I.e. `draw_connected(20)(gosper_curve(4));` will print the Drawing in the REPL

Fixed in https://github.com/source-academy/cadet-frontend/pull/719

> 5. I tested the library with [this version](https://github.com/source-academy/cadet-frontend/tree/25946d4c7045d28db8ed0353dc94c8ce837f5265) of cadet-frontend. The issues I had were mostly with some mistakes in the documentation mentioned above. I tried doing the missions 'Curve Introduction' and 'Curve Manipulation', and the pre-declared names are working well for these 2 missions at least.
>    Edit: I forgot that 'Gosperize and Diagnostics' as well as 'Diagnostics and Dragonize' are curve missions too. Will try them out as soon as I can

OK.
