### ISSUE TITLE
RUNES: Discussion on some (possibly) unexpected behaviours

### ISSUE THREAD

**Issue by chrisjwelly** [source-academy/js-slang#299]
Ran on [this branch](https://github.com/source-academy/cadet-frontend/tree/dcd16438de6d79543ef9e728077875f45d63cabb) of cadet-frontend
I'm not sure if the title of the issue is appropriate with respect to the content of this post, so feel free to change it!

1. For the function [`color(rune, r, g, b)`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#color), it is documented that the parameters take in values of `r`, `g`, and `b` from 0 - 255. However, if all 3 values are more than equal to 1, the rune becomes white. E.g. `show(color(square, 10, 1, 0));` vs `show(color(square, 10, 1, 2));` ([show in playground](https://sourceacademy.nus.edu.sg/playground#chap=1&ext=RUNES&prgrm=M4Cw9g7gFAxmA2YBOVgEcCuBDJBTANAAQCMADEcUaQJTUDcAUAPROGiSwLKqY4EnkSRAEy06QA))
    I suspect that the current implementation of `color` only allows the values of `r`, `g`, `b` to be between 0 - 1. E.g. `show(color(square, 0.5, 0.5, 0.5));` shows a grey square, which corresponds to be r = 128, g = 128, b = 128 in the 0 - 255 [RGB](https://www.rapidtables.com/web/color/RGB_Color.html) scale
    For users of this library, I think it is easier for them to use a 0 - 255 scale (and it has greater precision too I suppose), but if the usage of 0 - 1 scale is intended, then the documentation needs to be changed. Either way, it should be a simple case of multiplying/dividing by 255
2. [`beside_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#beside_frac), [`stack_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#stack_frac), [`overlay_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#overlay_frac) is supposed to have `frac` value between 0 - 1. However, negative values and values above 1 are also allowed. ([show in playground](https://sourceacademy.nus.edu.sg/playground#chap=1&ext=RUNES&prgrm=M4Cw9g7gFARgpsAlgEzgfQGYCcCGBjKABgDoBWAGgAI9Es8AbOKrRGGMAOwEouBuAKAD0gyqEiwEKdNnxQAtAEYqNOo2at23PkJFjo8JKky4CAJjLLaDJpRZtOPXkA))
    Should we try to validate the input values for `frac`?
3. [`rotate`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#rotate) function rotates the rune by a specified `rad` value in the anti-clockwise direction. I believe it is rotated with respect to the center of the rune. At certain rotation angles, the rune gets 'cropped off'.
    For example, `show(rotate(math_PI / 3, heart));`:
    ![](https://imgur.com/p3aOkfb.png)
    [Link to playground](https://sourceacademy.nus.edu.sg/playground#chap=1&ext=RUNES&prgrm=M4Cw9g7gFATmAuBDeBTKBbZID6AFAkgAQD0hAzADSEgqIzwCUDA3AFDGmiSwLJqbwcBEoQAsVYAEcArnRRM2HQl2hwkqDFjxFS4wgGMwMAHYoYC9p3CreGgUJ3kJMuQqA) for more examples. 
    As a student using the library, I would expect that the function simply rotates the relevant content of the rune and fits it to screen, instead of cropping it off. 

For points 2 and 3, arguably this allows for the possibility of some more creative runes. A possibility I can see is that for these "unexpected behaviours", we can create a new function abstraction entirely. E.g. much like `draw_connected_squeezed_to_window` vs `draw_connected` from the CURVES library for point 3

Edit: Regarding point 3, I just checked the mission 'Beyond the Second Dimension', and in that mission a function `translate` is provided. Runes that are translated will get 'cropped off' as well.

**Comment by openorclose** [comment]
> 2. [`beside_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#beside_frac), [`stack_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#stack_frac), [`overlay_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#overlay_frac) is supposed to have `frac` value between 0 - 1. However, negative values and values above 1 are also allowed. ([show in playground](https://sourceacademy.nus.edu.sg/playground#chap=1&ext=RUNES&prgrm=M4Cw9g7gFARgpsAlgEzgfQGYCcCGBjKABgDoBWAGgAI9Es8AbOKrRGGMAOwEouBuAKAD0gyqEiwEKdNnxQAtAEYqNOo2at23PkJFjo8JKky4CAJjLLaDJpRZtOPXkA))
>    Should we try to validate the input values for `frac`?

This is a more general issue that exists in many built in functions. 

e.g. `map(f, xs)` does not check if the first argument is a function and the second is a list.

Should we try to validate all of these?

**Comment by martin-henz** [comment]
> > 1. [`beside_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#beside_frac), [`stack_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#stack_frac), [`overlay_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#overlay_frac) is supposed to have `frac` value between 0 - 1. However, negative values and values above 1 are also allowed. ([show in playground](https://sourceacademy.nus.edu.sg/playground#chap=1&ext=RUNES&prgrm=M4Cw9g7gFARgpsAlgEzgfQGYCcCGBjKABgDoBWAGgAI9Es8AbOKrRGGMAOwEouBuAKAD0gyqEiwEKdNnxQAtAEYqNOo2at23PkJFjo8JKky4CAJjLLaDJpRZtOPXkA))
> >    Should we try to validate the input values for `frac`?
> 
> This is a more general issue that exists in many built in functions.
> 
> e.g. `map(f, xs)` does not check if the first argument is a function and the second is a list.
> 
> Should we try to validate all of these?

It's a trade-off between brevity/readability of programs and user convenience/safety. In our case, we've been using runtime checks quite sparingly. For example, head and tail use checks, but as you say map doesn't. The elegance of map would be compromised when we add these checks. The benefit I feel does not justify the effort. Similar with beside_frac etc. I feel that as long as we state the boundaries clearly, we don't need to always check them.

The issue is important, however. Students should be sensitive to the concepts of specification, constraints and error checking.

**Comment by martin-henz** [comment]
> Ran on [this branch](https://github.com/source-academy/cadet-frontend/tree/dcd16438de6d79543ef9e728077875f45d63cabb) of cadet-frontend
> I'm not sure if the title of the issue is appropriate with respect to the content of this post, so feel free to change it!
> 
> 1. For the function [`color(rune, r, g, b)`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#color), it is documented that the parameters take in values of `r`, `g`, and `b` from 0 - 255. However, if all 3 values are more than equal to 1, the rune becomes white. E.g. `show(color(square, 10, 1, 0));` vs `show(color(square, 10, 1, 2));` ([show in playground](https://sourceacademy.nus.edu.sg/playground#chap=1&ext=RUNES&prgrm=M4Cw9g7gFAxmA2YBOVgEcCuBDJBTANAAQCMADEcUaQJTUDcAUAPROGiSwLKqY4EnkSRAEy06QA))
>    I suspect that the current implementation of `color` only allows the values of `r`, `g`, `b` to be between 0 - 1. E.g. `show(color(square, 0.5, 0.5, 0.5));` shows a grey square, which corresponds to be r = 128, g = 128, b = 128 in the 0 - 255 [RGB](https://www.rapidtables.com/web/color/RGB_Color.html) scale
>    For users of this library, I think it is easier for them to use a 0 - 255 scale (and it has greater precision too I suppose), but if the usage of 0 - 1 scale is intended, then the documentation needs to be changed. Either way, it should be a simple case of multiplying/dividing by 255

Let's stick to the 0.0-1.0 range and adjust the doc. 

Done https://github.com/source-academy/cadet-frontend/pull/719

> 2. [`beside_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#beside_frac), [`stack_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#stack_frac), [`overlay_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#overlay_frac) is supposed to have `frac` value between 0 - 1. However, negative values and values above 1 are also allowed. ([show in playground](https://sourceacademy.nus.edu.sg/playground#chap=1&ext=RUNES&prgrm=M4Cw9g7gFARgpsAlgEzgfQGYCcCGBjKABgDoBWAGgAI9Es8AbOKrRGGMAOwEouBuAKAD0gyqEiwEKdNnxQAtAEYqNOo2at23PkJFjo8JKky4CAJjLLaDJpRZtOPXkA))
>    Should we try to validate the input values for `frac`?

I make a separate issue about this. Not sure if we have time for this.

> 3. [`rotate`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#rotate) function rotates the rune by a specified `rad` value in the anti-clockwise direction. I believe it is rotated with respect to the center of the rune. At certain rotation angles, the rune gets 'cropped off'.
>    For example, `show(rotate(math_PI / 3, heart));`:
>    ![](https://camo.githubusercontent.com/186a53e177542a8ca9fb8c3b0f796f61f082abc7/68747470733a2f2f696d6775722e636f6d2f7033614f6b66622e706e67)
>    [Link to playground](https://sourceacademy.nus.edu.sg/playground#chap=1&ext=RUNES&prgrm=M4Cw9g7gFATmAuBDeBTKBbZID6AFAkgAQD0hAzADSEgqIzwCUDA3AFDGmiSwLJqbwcBEoQAsVYAEcArnRRM2HQl2hwkqDFjxFS4wgGMwMAHYoYC9p3CreGgUJ3kJMuQqA) for more examples.
>    As a student using the library, I would expect that the function simply rotates the relevant content of the rune and fits it to screen, instead of cropping it off.
> 
> For points 2 and 3, arguably this allows for the possibility of some more creative runes. A possibility I can see is that for these "unexpected behaviours", we can create a new function abstraction entirely. E.g. much like `draw_connected_squeezed_to_window` vs `draw_connected` from the CURVES library for point 3
> 
> Edit: Regarding point 3, I just checked the mission 'Beyond the Second Dimension', and in that mission a function `translate` is provided. Runes that are translated will get 'cropped off' as well.

Yes, I'll add a warning to the rotate doc.

Done https://github.com/source-academy/cadet-frontend/pull/719
