### ISSUE TITLE
DOC: Comments on RUNES documentation

### ISSUE THREAD

**Issue by chrisjwelly** [source-academy/js-slang#300]
Should I try to compile my comments on the documentation into one, instead of opening a separate issue for the different sections? This is perhaps a little too repetitive, but I did not want to throw a large chunk of comments on different sections into a single issue, and some parts may be missed out by the reader if I keep updating the same post

Anyway, some comments I have regarding the [RUNES documentation](https://sicp.comp.nus.edu.sg/source/RUNES/index.html):
1. Like raised in #295 , we could try to provide more information on the basic usage of these libraries, which have been explained in the missions. Runes are more intuitive to use than Curves, so I don't suppose that this is as urgent as adding the usage information for Curves
2. [`beside_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#beside_frac), [`stack_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#stack_frac), [`overlay_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#overlay_frac): have the wrong order of parameters. It should be `beside_frac(frac, rune1, rune2)` while in the current documentation it is `beside_frac(rune1, rune2, frac)`
3. Redundant word in all the coloring functions: 'colors the **give** given rune [color]. ' The colors are: 
    * [black](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#black)
    * [blue](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#blue)
    * [brown](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#brown)
    * [green](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#green)
    * [indigo](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#indigo)
    * [red](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#red)
    * [orange](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#orange)
    * [pink](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#pink)
    * [purple](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#purple)
    * [white](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#white)
    * [yellow](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#yellow)
4. For the coloring functions above, should we specify that it returns a Rune? Currently, it does not seem to have a return type in the documentation
5. [`random_color`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#random_color): is described as: "The color is chosen randomly from the nine given colors below". However, the nine colors are not really shown "below" this description
6. In light of point 5, I think it would be good if the coloring functions have its own section in the page. This is so that a person referring to the docs can easily look for the available default colors. This also includes function like `random_color`. Currently, these colors are scattered under 'functions' which are listed in alphabetical order.
7. For the Constants (specifically, Runes in our case), I think it would be good to possibly attach a picture of the individual corresponding Runes in the docs rather than just describing it! 
8. [`color`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#color): Wrote a short discussion about the values of `r`, `g`, `b` in the first point of #299 . If we decide on the values to be 0 - 1, then the docs will need a corresponding change as well. 
9. Opacity is mentioned in the description for `color`, but we never explained what it is in the docs nor in the missions (although it is plain English, and people should still understand what it means). Since no other function directly manipulates the opacity, we could exclude it from the description, or add more details about it.

**Comment by martin-henz** [comment]
separate is best. Thanks so much for taking a close look!

**Comment by martin-henz** [comment]
> Should I try to compile my comments on the documentation into one, instead of opening a separate issue for the different sections? This is perhaps a little too repetitive, but I did not want to throw a large chunk of comments on different sections into a single issue, and some parts may be missed out by the reader if I keep updating the same post
> 
> Anyway, some comments I have regarding the [RUNES documentation](https://sicp.comp.nus.edu.sg/source/RUNES/index.html):
> 
> 1. Like raised in #295 , we could try to provide more information on the basic usage of these libraries, which have been explained in the missions. Runes are more intuitive to use than Curves, so I don't suppose that this is as urgent as adding the usage information for Curves

Yes, I think textbook reference is enough for this.

> 2. [`beside_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#beside_frac), [`stack_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#stack_frac), [`overlay_frac`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#overlay_frac): have the wrong order of parameters. It should be `beside_frac(frac, rune1, rune2)` while in the current documentation it is `beside_frac(rune1, rune2, frac)`

Done https://github.com/source-academy/cadet-frontend/pull/719

> 3. Redundant word in all the coloring functions: 'colors the **give** given rune [color]. ' The colors are:
>    
>    * [black](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#black)
>    * [blue](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#blue)
>    * [brown](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#brown)
>    * [green](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#green)
>    * [indigo](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#indigo)
>    * [red](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#red)
>    * [orange](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#orange)
>    * [pink](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#pink)
>    * [purple](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#purple)
>    * [white](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#white)
>    * [yellow](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#yellow)

Done in https://github.com/source-academy/cadet-frontend/pull/719

> 4. For the coloring functions above, should we specify that it returns a Rune? Currently, it does not seem to have a return type in the documentation

Done in https://github.com/source-academy/cadet-frontend/pull/719

> 5. [`random_color`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#random_color): is described as: "The color is chosen randomly from the nine given colors below". However, the nine colors are not really shown "below" this description

Done in https://github.com/source-academy/cadet-frontend/pull/719

> 6. In light of point 5, I think it would be good if the coloring functions have its own section in the page. This is so that a person referring to the docs can easily look for the available default colors. This also includes function like `random_color`. Currently, these colors are scattered under 'functions' which are listed in alphabetical order.

Yes, would be good but requires more work in the formatting. Will make an issue.

> 7. For the Constants (specifically, Runes in our case), I think it would be good to possibly attach a picture of the individual corresponding Runes in the docs rather than just describing it!

Yes, good idea. Also in new issue.

> 8. [`color`](https://sicp.comp.nus.edu.sg/source/RUNES/global.html#color): Wrote a short discussion about the values of `r`, `g`, `b` in the first point of #299 . If we decide on the values to be 0 - 1, then the docs will need a corresponding change as well.

Done.

> 9. Opacity is mentioned in the description for `color`, but we never explained what it is in the docs nor in the missions (although it is plain English, and people should still understand what it means). Since no other function directly manipulates the opacity, we could exclude it from the description, or add more details about it.

Done in https://github.com/source-academy/cadet-frontend/pull/719
