### ISSUE TITLE
LANG: Constants can be redefined with "const"

### ISSUE THREAD

**Issue by alcen** [source-academy/js-slang#302]
When variables are defined with `const`, they cannot be reassigned or redefined with `let`. But it seems like they can be redefined with the `const` keyword.

![constant redefined1](https://user-images.githubusercontent.com/49450743/61211624-a29e5680-a732-11e9-831f-1f85b2b47c9b.png)

&nbsp;

A side effect of this is that native functions and values can be redefined.

![constant redefined2](https://user-images.githubusercontent.com/49450743/61211632-a631dd80-a732-11e9-977e-18ced85fe1ea.png)

**Comment by martin-henz** [comment]
This is a bug fix and not a bug. The new meaning of the Source Academy is this:

Primitive and predeclared: imaginary program that declares things like math_PI and map

Student program S1 gets added implicitly in a block:

{
S1
*
}

Student program S2 gets evaluated in a new block at position *:

{
S1
{
S2
*
}
}

and student program S3:

{
S1
{
S2
{
S3
*
}
}
}

The old values are still there, they are just not visible by the new student program. 

This is the usual way of handling scope in interactive programming environments with lexical scoping. It gives interactivity, and a clear semantics.

**Comment by martin-henz** [comment]
The good thing about this: the students (and lecturer) can interactively re-define pre-declared functions. 

Having said that, there is currently a bug in this implementation:

<img width="308" alt="Screenshot 2019-07-15 at 8 11 37 PM" src="https://user-images.githubusercontent.com/30220768/61215274-f4e47500-a73c-11e9-8938-b42cf5d94e9a.png">

The last line is supposed to show the original map. Daryl is working on this.

**Comment by martin-henz** [comment]
See https://github.com/source-academy/js-slang/issues/288

**Comment by alcen** [comment]
Ok, thanks for explaining this. So I guess the REPL is running in a different scope now?

**Comment by martin-henz** [comment]
It's more like this:

Every program entered by the student opens a new scope. It implicitly has its own block. The blocks are arranged such that the declarations of previous programs are visible, using the usual rules for nested blocks.

**Comment by martin-henz** [comment]
This will all be quite natural and automatic for the students. However, the observant students will ask this at some point, so it's good if we all have a consistent explanation.
