### ISSUE TITLE
debugger/breakpoints seem to clear environment?

### ISSUE THREAD

**Issue by thomastanck** [source-academy/js-slang#304]
![scrrec](https://user-images.githubusercontent.com/829070/61280514-9675d000-a7ea-11e9-8036-17ba89e7f81c.gif)

```
const z = 1;
debugger;
z;
```

Stops at the breakpoint, then after resuming, shows the error: `Line 3: Name z not declared.`

Program works as expected after removing the debugger statement.

Same issue happens with a breakpoint at `z;`.

**Comment by openorclose** [comment]
Is this on https://sourceacademy.nus.edu.sg/playground?

I just tried it there and can't reproduce. I'm on Edge Chromium and it seems like you're using Firefox?

**Comment by thomastanck** [comment]
Yep, on the playground, using Firefox. Just checked and still getting the same error.

**Comment by openorclose** [comment]
I just downloaded Firefox, can reproduce.

**Comment by martin-henz** [comment]
No problem any longer, even with Firefox.
