### ISSUE TITLE
DOC: HTML tags appear in browser tab title 

### ISSUE THREAD

**Issue by chrisjwelly** [source-academy/js-slang#306]
I think this is an unintended consequence of this commit 2d69e53ce888454b9df3415bce317a90151a7f9f? 

For pages showing all the predeclared names, HTML tags appear in browser tab title as shown in the screenshots below:

![](https://imgur.com/t7TCnPr.png)
![](https://imgur.com/LBfwJLR.png)

**Comment by martin-henz** [comment]
Ha, yes, surely unintended!

**Comment by martin-henz** [comment]
Handled by: https://github.com/source-academy/js-slang/pull/271
