### ISSUE TITLE
Documentation: No line break between parameters and arrow

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#32]
Line break disallowed between parameters and arrow: Correct: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Line_breaks

Need to update the Source docs.

**Comment by ningyuansg** [comment]
May I take this time to advocate for a [feature branch workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow), and commit messages following [good practices](https://github.com/erlang/otp/wiki/writing-good-commit-messages)?

**Comment by martin-henz** [comment]
Yes, let's use the feature branch workflow for all our repositories, github and bitbucket. Can you change the js-lang to prevent pushing to master, if it isn't done yet? Tx.

**Comment by ningyuansg** [comment]
Done!

**Comment by ningyuansg** [comment]
Fixed with https://github.com/source-academy/js-slang/pull/35.
