### ISSUE TITLE
Use git submodules?

### ISSUE THREAD

**Issue by geshuming** [source-academy/js-slang#324]
js-slang is used exclusively by source academy. In that case, rather than publishing versions onto npm, we should just use it as a submodule for frontend and grader.

**Comment by martin-henz** [comment]
The ambition is for js-slang to exist independently of the Source Academy. I think it's good to keep it as a (potentially) independent repository.

**Comment by thomastanck** [comment]
Reopening this because I think there is some miscommunication here. Using git submodules means that js-slang remains an independent repository. Instead, what would change is that frontend/grader would explicitly include a reference to a specific commit in this repository that they will use to build, rather than fetching the copy of js-slang from the npm.

**Comment by martin-henz** [comment]
Oh, indeed, I didnt catch the intention, although Shuming made it clear.

**Comment by martin-henz** [comment]
@martin-henz will ask the steering committee about this.

**Comment by martin-henz** [comment]
We are now using submodules within js-slang. Using js-slang as a submodule in frontend might complicate things too much. I feel that the current separate deployment of js-slang allows us to keep frontend somewhat independent of js-slang. So I'd vote for keeping things as they are.

**Comment by RichDom2185** [comment]
Though using submodules within js-slang does not present an issue (it's fully abstracted by git), I agree that having a separate NPM deployment makes things less coupled and also helps to enforce some degree of independence/abstraction between what should be under js-slang and what should be under frontend.

As discussed over Telegram, we will close this issue for now.
