### ISSUE TITLE
Strange error message involving undefined

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#333]
Evaluating
```
function mosaic(r1, r2, r3, r4) {
    // your answer here
}

// Test
show(mosaic(rcross, sail, corner, nova));
```

gives:

```
Line 6: TypeError: Cannot read property 'isPrimary' of undefined
```

This error message will be rather cryptic for students.

**Comment by openorclose** [comment]
Yes, this is a problem. We can change the `show` function in cadet-frontend to check for the proper object.

**Comment by martin-henz** [comment]
Maybe we can include this in the next version of js-slang, along with the fixes required for the substituter?

**Comment by martin-henz** [comment]
Error message is now:
Line 6: show expects a rune as argument, received undefined

That's fine.
