### ISSUE TITLE
Eval_stream bug

### ISSUE THREAD

**Issue by lwlshawn** [source-academy/js-slang#363]
Eval_Stream as it is currently written evaluates one element too many:

function eval_stream(s, n) {
    return n === 0 ? null : pair(head(s), eval_stream(stream_tail(s), n - 1));
}

For example, calling eval_stream(s, 3) will evaluate 3 elements, and throw the last element away.
A possible fix would be just changing n === 0 ? to n === 1.

**Comment by martin-henz** [comment]
Thanks for spotting this @lwlshawn. A minor issue that we should fix next year.
