### ISSUE TITLE
Error running js-slang on command line

### ISSUE THREAD

**Issue by tjtanjin** [source-academy/js-slang#369]
After installing js-slang with npm (tried on macOS and Ubuntu 18.0.4), running js-slang on the command line throws the following error:

<img width="679" alt="Screenshot 2019-11-08 at 6 21 01 PM" src="https://user-images.githubusercontent.com/43908963/68469540-56cd6b00-0255-11ea-86fa-32aa7d6c2772.png">

**Comment by lamlaaaam** [comment]
Similar issue on Windows 10, seems to be also in repl.js (line 3)
![image](https://user-images.githubusercontent.com/57550403/68529448-e1879600-0339-11ea-964e-49c795730857.png)

**Comment by martin-henz** [comment]
looks like a mis-reading of the README
