### ISSUE TITLE
Compile source_week_* in make all

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/js-slang#37]
But exclude from `make install`.

> Sorry, I missed these comments. Good points. Yes, let's include the Week 1 document in
> make all
> but exclude it from
> make install
> 
> Can you please change the Makefile accordingly?
> 
> Thanks,
> 
> -martin

See: https://github.com/source-academy/js-slang/pull/34#issuecomment-415083636

**Comment by martin-henz** [comment]
done
