### ISSUE TITLE
Function prompt should return undefined when cancel is pressed

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#39]
Currently, the return value is null. The null value is not part of Source, so this leaves a weird hole in the specs. I propose to return undefined, so that student can write:
const answer = prompt("What is your answer?");
if (answer === undefined) { .... } else { ... }

**Comment by martin-henz** [comment]
Let's follow whatever JS does.

**Comment by openorclose** [comment]
No, I don't think so. We should make sure that null is only used for the empty list and nothing else. 

Otherwise, it would create unnecessary confusion over undefined and null.

**Comment by jiachen247** [comment]
@openorclose that makes sense! 

okay, I guess it comes down to if we want to be with the browser implementation based of the html spec for the window object or we want to be consistent with source and maintain null only to terminate the empty list.

Perhaps updating the source documentation to include this would be helpful!

If everyone is agreeable, I think we can close this and move this to the cadet-frontend.

**Comment by openorclose** [comment]
Why not we return null, but provide an is_cancel_pressed function to abstract it away?

**Comment by thomastanck** [comment]
Good idea. I agree.

**Comment by martin-henz** [comment]
OK, let's do this: 
prompt(s)
is_prompt_cancel_pressed(x)

**Comment by thomastanck** [comment]
> We just specify (consistent with JS) that prompt returns a non-string value in the case when Cancel is pressed.

Oh! That's a nice idea! I completely agree. In this case all we need to do is write this into the docs. No (further) language changes are required.

**Comment by martin-henz** [comment]
OK, handled by PR "136 and 39"
