### ISSUE TITLE
Proposal: import syntax for Source §1-§4

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#399]
I'm proposing to allow the following syntax in Source:

```
program         ::= importdirective... statement...
importdirective ::= import { importnames } from string;
importnames     ::= importname (, importname)...
importname      ::= name | name as name
```

This means that we will explicitly import modules (libraries) from now on, in order to use them:

```
import { heart as lung, show as view, stack, sail } from 'lib/runes';

view(stack(lung, sail));
```

This will:
* demystify module loading for students: Source would be in line with other programming languages where imported functionality is explicitly named in programs
* simplify the Source Academy user interface: no more need for a "Library" menu
* simplify js-slang tools: imported names are all explicitly mentioned in the program

For Source 2021, the path will be resolved to:
`https://github.com/source-academy/modules/tree/master/`
This means that `from 'lib/runes'` refers to
`https://github.com/source-academy/modules/tree/master/lib/runes.js` (the default file extension will be .js)

The Source Academy frontend will fetch the module from the backend, which of course will cache it. Our modules can still be written in JavaScript and loaded in the frontend in whatever way works (e.g. eval).

In the future, we can allow for a more flexible scheme where users can import Source programs using the same syntax.

**Comment by openorclose** [comment]
Yes, I think that's a good suggestion.

Ideally we would also have some sort of autoimport feature built into Ace (since it's really troublesome to have to keep adding library functions to the import statment in the midst of solving a mission).

Otherwise I can foresee this "header file" that includes all library functions being prepended to Source programs which would defeat the purpose of this.

Haven't gave it too much thought on the implementation side.

**Comment by martin-henz** [comment]
For solving missions, our template would already provide a sufficient import directive, and the students would be advised not to change it.

**Comment by btzy** [comment]
> `program         ::= importdirective... statement`

Shouldn't a program be allowed to contain more than one statement?

**Comment by martin-henz** [comment]
You are right. It should be statement...

**Comment by btzy** [comment]
I would recommend allowing aliased imports for ease of implementation.  I think it is impossible (without hacks) to differentiate between `import {foo} from "file";` and `import {foo as foo} from "file";` in an ESTree.

**Comment by martin-henz** [comment]
> I would recommend allowing aliased imports for ease of implementation. I think it is impossible (without hacks) to differentiate between `import {foo} from "file";` and `import {foo as foo} from "file";` in an ESTree.

I agree. I've changed the proposal above accordingly.
