### ISSUE TITLE
Support for template literals

### ISSUE THREAD

**Issue by openorclose** [source-academy/js-slang#400]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

Not sure if supporting the `` `${expr}`  `` syntax is helpful, but with template literals it gets a lot easier to write multiline strings for language evaluators:

```js
const program=`
const a = 1;
const b = 2;
`;

**Comment by martin-henz** [comment]
Yes, let's do this, first without ${...}. It's obviously beneficial, and doesn't cost much extra explanation: we already have two kinds of quotes:
"
'
Supporting a third one costs us just a few extra characters in the language descriptions.
