### ISSUE TITLE
SUBST: freezes and does not timeout for long-running code

### ISSUE THREAD

**Issue by btzy** [source-academy/js-slang#409]
**Test case:**

Use the following code.  Set a breakpoint at the line `const x=0;` to invoke the interpreter.
```
function test(){
    test();
    const x=0;
}
test();
```
Then run the code.

**Actual behaviour:**

Source Academy freezes forever.

**Expected behaviour:**

It should stop running and print a timeout message.

**Comment by martin-henz** [comment]
This is the current behaviour for Source §1, which uses a stepper (small step semantics), aka substituter.

**Comment by martin-henz** [comment]
This bug is subsumed by: https://github.com/source-academy/js-slang/issues/367
