### ISSUE TITLE
Style guide: line break making arrow function invalid

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/js-slang#41]
A fix is needed for the style guide in the function definition section.

![image](https://user-images.githubusercontent.com/11135744/44629633-c161f600-a984-11e8-911f-dcb41beb1fef.png)

From MDN:
> An arrow function cannot contain a line break between its parameters and its arrow.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Line_breaks

**Comment by martin-henz** [comment]
fixed by new style guide
