### ISSUE TITLE
FOR: assignment to loop control variable

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#411]
```
for(let i=0;i<4;i=i+1){
    i = i + 1;
 display(i);
}
```
should be rejected at compile time, following the Source §3 specs.

It currently runs without problems.

**Comment by openorclose** [comment]
https://source-academy.github.io/playground#chap=1&exec=1000&ext=NONE&prgrm=GYVwdgxgLglg9mABAZwI4gIYCcCmAKADwEpEBvAKESsVyhCyQMQCpECBucgX3NElgQoAthgA2onMigB9ACYwAbjGRwseMCQrUaOOg0TAYYWXMXLV6gDSIATEU48%2B0eEkPHTSlWrDWokmfKeqpqU2rT0SGiYuHh%2BUh7mWCQAfIhgodqZiAD8aRlZ1ABciIEwspKx-gle1hr5BdS5cQFmXvUNiMVuJqVeVojN1aqIANSIAIz23LzgzoKl5ch4GNYARiFhuhGIq4gApIgYiAC8p4gADA4z-C6IytIADlgwQvgaZPnh%2Bkinx8JiEnivQsGiuTgESFgrxMTxeOGkzXUG2o8mQD1EGAAnkjOJs9JEoNgZLDXgj-P0sOAofgiFNHLMIShCVhic9SYifEyiQi4ciqF8kPcSW8iO1MrlcA9VKy4XhKWBqXgSABaLksnmvUUdKjFKCUnBghm3SXSx5s-A4DEPZA4EzUvklZTorF4ABELGYrFdU20qOd2MtGGtto1ODp5HI1Jh5rJUjwAE5E0nkwAOeP2IA

Seems fixed.

Someone else verify and close?

**Comment by martin-henz** [comment]
Yes, I checked all variants of §3 and §4. It's fixed.
