### ISSUE TITLE
try / finally blocks are allowed but do nothing

### ISSUE THREAD

**Issue by Caephler** [source-academy/js-slang#47]
try / finally blocks should not be allowed but they are in Source. (tried in both S1 and S2)
Sample code:
```
try {
    display("1");
} finally {
    display("2");
}
```
Both ```display``` calls do not run, but the interpreter does not throw an error. Including a catch block will still result in an error, which is working as intended.

**Comment by thomastanck** [comment]
Closing in favour of #129, a combination of a bunch of issues, to clean up the list of issues a little.
