### ISSUE TITLE
parse_int function does not match ECMAscript specification

### ISSUE THREAD

**Issue by Wingedevil** [source-academy/js-slang#52]
```
parse_int("1",36); // returns 1 intended behavior
parse_int("1",46);
parse_int("uu1",36);
```

```"Error: parseInt expects two arguments a string s, and a positive integer i"``` is thrown while both arguments are as stated in the error. In addition, according to ECMAScript specification, a ```NaN``` is returned for these two cases.

**Comment by ningyuansg** [comment]
@martin-henz Are we following ES specs and returning `NaN` here?

@Wingedevil Either way, the fix is quite trivial. You can try it yourself if you like at https://github.com/source-academy/js-slang/blob/3464f4d35d1c16ef7ef367a97d1535320180c3d1/src/stdlib/misc.ts#L48. Otherwise, somebody will fix this soon.

**Comment by martin-henz** [comment]
Yes, of course. We are following ES specs. Note that the second argument is not optional in Source. As usual, Source is clearer and simpler than ES, but everything that runs in Source should run exactly in the same way in any native ES implementation.

**Comment by martin-henz** [comment]
> Yes, of course. We are following ES specs. Note that the second argument is not optional in Source. 

Yes, of course. We are following ES specs. Note that the second argument is not optional in Source. As usual, Source is clearer and simpler than ES, but everything that runs in Source should run exactly in the same way in any native ES implementation.

**Comment by martin-henz** [comment]
> @martin-henz Are we following ES specs and returning `NaN` here?

Yes, of course. We are following ES specs. Note that the second argument is not optional in Source. As usual, Source is clearer and simpler than ES, but everything that runs in Source should run exactly in the same way in any native ES implementation.
