### ISSUE TITLE
Evaluation of toplevel statement sequences

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#537]
```3; {}``` should give 3.
```3; const x = 1;``` should give 3.

A proposal for a specs: The result of evaluating a sequence of statements (outside of any functions) is the result of evaluating the last value-producing statement in the sequence. Any expression statement, assignment statement, conditional statement, for-loop and while loop is value-producing. A block containing a sequence of statements is value producing if any of these statements is value-producing. The result of evaluating a while or for loop is the result of evaluating the body in its last iteration, or undefined if the body of the loop does not get evaluated at all. The result of evaluating a conditional statement is the result of evaluating the correct branch. The result of evaluating the empty sequence of statements is undefined.

 This comes from page 249 of ES2019, https://www.ecma-international.org/publications/standards/Ecma-262.htm

<img width="624" alt="Screenshot 2020-04-13 at 12 21 09 PM" src="https://user-images.githubusercontent.com/30220768/79171882-c576ac00-7e25-11ea-92db-43a68b7c931c.png">

**Comment by btzy** [comment]
I think there would be a slight complication here.  In JavaScript, assignment is also a value-producing statement, but not in Source.

Source specs will need to clearly specify the result of evaluating an assignment in the top-level, e.g.:
```
let x = 1;
x = 2;
```

**Comment by btzy** [comment]
> The result of evaluating the empty sequence of statements is undefined.

This doesn't seem correct.  If it was correct, then `eval("1;{}")` would return `undefined`.

**Comment by martin-henz** [comment]
> > The result of evaluating the empty sequence of statements is undefined.
> 
> This doesn't seem correct. If it was correct, then `eval("1;{}")` would return `undefined`, since `{}` is an empty sequence of statements.

An empty block is not value-producing. That explains the result 1 of `eval("1;{}")`.

**Comment by martin-henz** [comment]
I'm having second thoughts about this. So much work for all the implementations, and as a result, the language gets uglier. The benefit would be adherence to JavaScript, for cases that don't matter much in practice. At the moment we say this in the Source specs:

<img width="685" alt="Screenshot 2020-04-20 at 8 42 29 AM" src="https://user-images.githubusercontent.com/30220768/79704292-5399d900-82e3-11ea-9d00-d443c4bed41f.png">

I'm thinking of just tightening the last paragraph, following our improved understanding of this JavaScript feature.

**Comment by martin-henz** [comment]
> I think there would be a slight complication here. In JavaScript, assignment is an expression (and hence value-producing), but not in Source.
> 
> Source specs will need to clearly specify the result of evaluating an assignment in the top-level, e.g.:
> 
> ```
> let x = 1;
> x = 2;
> ```

fixed in first post above.

**Comment by martin-henz** [comment]
A telegram discussion with @btzy led to the following proposals:

(1) Status quo, with better documentation:

Every statement produces a value, which is displayed as the result of the program. Expression statements and assignment statements produce the result of evaluating their expressions. A block produces whatever its body statement produces. A (constant, variable, function) declaration produces undefined.
A sequence produces the value of its last statement, or undefined if the sequence is empty ( {} ). Conditional statements produce whatever the chosen branch produces. Loops produce the result of their last loop body execution, and undefined if the loop body is not executed.

(2) Simplification

The value produced by a program is:
- the result of evaluating e, if the last statement is an expression statement e;
- undefined, otherwise

Proposal (2) is simpler than (1), but further away from JS. An added advantage of Proposal (1)  is that it's what is already implemented, and updating all implementations would be quite a pain.

**Comment by btzy** [comment]
Another advantage of Proposal (2) is that we would not need to differentiate between _producing_ a value and the normal notion of _returning_ a value.

In the status quo, assignment statements, let/const declarations, and blocks _produce_ a value even though they do not _return_ a value (so they can't be used in an expression).  For example: `x = 2;` _produces_ 2, and `{}` _produces_ `undefined`, even though neither of them _return_ a value.  This means that those statements in Source can produce values that cannot be accessed from within Source, but can be accessed by the host environment -- it could be argued that this is rather surprising.

**Comment by martin-henz** [comment]
Alternative (3) is the JavaScript way:

A proposal for a specs: The result of evaluating a sequence of statements (outside of any functions) is the result of evaluating the last value-producing statement in the sequence. Any expression statement, assignment statement, conditional statement, for-loop and while loop is value-producing. A block containing a sequence of statements is value producing if any of these statements is value-producing. The result of evaluating a while or for loop is the result of evaluating the body in its last iteration, or undefined if the body of the loop does not get evaluated at all. The result of evaluating a conditional statement is the result of evaluating the correct branch. The result of evaluating the empty sequence of statements is undefined.

another attempt at describing it would be:

The result of evaluating a sequence of statements (outside of any functions) is the result of evaluating the last statement in the sequence, where declarations are ignored. A block containing a sequence of statements is ignored if it only contains declarations. The result of evaluating a while or for loop is the result of evaluating the body in its last iteration, or undefined if the body of the loop does not get evaluated at all. The result of evaluating a conditional statement is the result of evaluating the correct branch. The result of evaluating the empty sequence of statements is undefined.

**Comment by martin-henz** [comment]
Advantages of Alternative (3): 

(a) It is the same as JavaScript, which is a huge benefit, because anything else will open us to the criticism that Source is not JavaScript and thus SICP JS is a fraud.

(b) It supports the following incremental development pattern: 
```
function f(x) {...}
// test case for f
f(3);

function g(x) {...}

// test case for g
//g(4);

function h(x) {...}

//test case for h
//h(5);
```
To see the result of the test cases we just need to un-comment whichever case we want, in the example the first one.

**Comment by martin-henz** [comment]
[this issue is turning into a stream-of-consciousness]

Update: Just got tripped up by for loops: Background: We are adding an optimization that parallelizes for loops that meet certain conditions, using gpu.js. JS semantics that toplevel loops return the value of the last execution of the loop is unsustainable when we parallelize them. 

This leads us away from Alternative (3). To keep that optimization clean and simple, I suggest we go for Alternative (2).

**Comment by martin-henz** [comment]
We will not have the time to fix this issue permanently and satisfactorily before the semester starts. So I have added this as a section of "Deviations from JavaScript" in the specs (https://source-academy.github.io/source/) and added an exercise on it to the textbook: https://source-academy.github.io/sicp/chapters/4.1.2.html#ex_4.9
@btzy @yyc @openorclose any comments welcome.

**Comment by martin-henz** [comment]
This has been fixed for the transpiler. The transpiler seems to be compliant with JavaScript on this, including loops.
