### ISSUE TITLE
Stepper: Evaluation of toplevel statement sequences

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#539]
See https://github.com/source-academy/js-slang/issues/537

**Comment by martin-henz** [comment]
See here for current status: https://github.com/source-academy/js-slang/issues/537#issuecomment-662235762

**Comment by parnikkapore** [comment]
(reopening this to wait for the implementation - shouldn't have tagged the issues!)

**Comment by martin-henz** [comment]
To clarify why this issue is still open: All evaluation paths handle 
```
3; {} // should produce 3
```
correctly, except the stepper. It is also fixed in the stepper specs, but not yet in the stepper implementation.

**Comment by hanscau** [comment]
Solved by #1565
