### ISSUE TITLE
Specs Proposal: Split predeclared library names from Names section

### ISSUE THREAD

**Issue by btzy** [source-academy/js-slang#568]
The "Names" section in the specification contain two rather distinct things:

- The allowable characters that make a valid name (a language concern)
- The standard library names that are predeclared in Source (a library concern)

These two concerns should not be mixed in the same section because they are quite different in nature.

I propose that the "Names" section should only contain the language concerns, and a separate "Standard Library" section should contain the definition of the standard library functions, and also specifies that:

- Source has some predeclared names, which act as if the following line was prefixed to the program: `import * from '/* implementation defined library location */';`  (This definition of predeclared names allow them to be shadowed by variables with the same name declared by the user.)

**Comment by martin-henz** [comment]
I agree. Will try to fix this.
