### ISSUE TITLE
Library: display(v, s) does not ensure that the second argument is a string

### ISSUE THREAD

**Issue by btzy** [source-academy/js-slang#583]
Run the following code in Source Academy:

```
display("test",100);
display("test",true);
display("test",()=>{});
```

It runs without errors and produces:

```
100 "test"
true "test"
() => {} "test"
```

This is not the correct behaviour as per the library documentation.  The library documentation states that the second argument must be a string:

![image](https://user-images.githubusercontent.com/6948096/80560895-2f41a900-8a15-11ea-9019-57d648db07d1.png)

The correct behaviour should be a compilation or runtime error (at least, some error should be produced).

`error(v, s)` has the same issue.

**Comment by martin-henz** [comment]
We could accept this as an undocumented feature. If we fix it, let's remember to change the type inferencer, too.

**Comment by thomastanck** [comment]
> We could accept this as an undocumented feature. If we fix it, let's remember to change the type inferencer, too.

Looking at the type inferencer, supporting more than one type signature isn't a couple lines change. I think we can close this issue when #700 gets merged, and I'll make a new issue for type checking of `display`.
