### ISSUE TITLE
null instead of []

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#60]
JavaScript has a value null, which has just the right connotation for empty lists. So from 2019 onwards, a list will be:

either the value null or a pair whose tail is a list

The test is_empty_list should be replaced by === null, as is customary in JavaScript.

**Comment by remo5000** [comment]
For future reference, feel free to make a `2019` tag. This might come in handy for CP3108 as well 👍

**Comment by openorclose** [comment]
Reopening this.

It's only valid syntax now, but the logic for pairs is not yet implemented. 

I'm working on it.

**Comment by openorclose** [comment]
Resolved in #143
