### ISSUE TITLE
Infinite Loop Detector does not take into account short-circuiting

### ISSUE THREAD

**Issue by JoeyChenSmart** [source-academy/js-slang#605]
Example code:
```
function fac(x) {
    if (x===0) {
        return false;
    } else {
        return true || fac(x-1);
    }
}
fac(-2);
```
This code should terminate, however the infinite loop detector (incorrectly) assumes both branches of logical expressions (`true || fac(x-1)` in this case) will be executed.

**Comment by martin-henz** [comment]
I cant reproduce this error. Is it fixed?

**Comment by martin-henz** [comment]
@JoeyChenSmart confirmed its fixed.
