### ISSUE TITLE
Modules: Importing names with alias not working

### ISSUE THREAD

**Issue by btzy** [source-academy/js-slang#618]
It is best to explain using an example:

**1. Importing name without alias, works as expected:**
![image](https://user-images.githubusercontent.com/6948096/81469710-1c9b5100-9219-11ea-82e1-20dd665de358.png)

**2. Undeclared variable, errors out as expected:**
![image](https://user-images.githubusercontent.com/6948096/81469742-510f0d00-9219-11ea-9562-633fe41d51a6.png)

**3. Importing name with alias, ... some cryptic error message:**
![image](https://user-images.githubusercontent.com/6948096/81469750-697f2780-9219-11ea-9c4c-062f3ebe17e2.png)

The fact that (2) and (3) do not lead to the same error suggests that js-slang recognises the alias import somewhat... but apparently `t` is undefined so the code does not work.  If aliases are not allowed then the error message should be fixed.

**Comment by martin-henz** [comment]
Either we (1) support and add to the specs or we (2) generate an error message when this is attempted.

**Comment by Anonymxtrix** [comment]
Closing because resolved. See [here](https://github.com/source-academy/modules/issues/59).
