### ISSUE TITLE
Critical for loop issues

### ISSUE THREAD

**Issue by openorclose** [source-academy/js-slang#65]
a) Now the following valid es2015 code results in an error:

```javascript
function test(){
      for (let x = 0; x < 10; x = x + 1) {
        let x = 1; //Error on this line, should be valid
      }
}
test();
```

```let``` statements should still be block scoped in the body of a for loop.

b) Another problem:

```javascript
function test(){
      let timesRun = 0;
      for (let x = 0; x < 10; x = x + 1) {
        timesRun = timesRun + 1;
        x = x + 1;
      }
      return timesRun;
}
test();
```
The loop should only run five times as x is updated in the loop, but due to shallow copying of the environment variables into the new frame, x is not updated as it should be.

**Comment by openorclose** [comment]
@martin-henz What about (b)? Should mutating of variables declared in the first expression during the body of the loop be allowed?

```javascript
function test(){
      let timesRun = 0;
      for (let x = 0; x < 10; x = x + 1) {
        timesRun = timesRun + 1;
        x = x + 1;
      }
      return timesRun;
}
test(); //currently returns 10, should return 5 or not?

**Comment by martin-henz** [comment]
Yes, I would expect this example to return 5.

Variables that are introduce with let should be freely readable and writable within their scope. The scope of variables that are declared in the statement after "for" should be the entire for-loop.

Regarding implementation: Do we have the notion of a "block" in the implementation? If yes, we could just translate the program into this, internally:

function test(){
      let timesRun = 0;
    {
      let x = 0;
      for (; x < 10; x = x + 1) {
        timesRun = timesRun + 1;
        x = x + 1;
      }
    }
      return timesRun;
}
test(); //currently returns 10, should return 5 or not?

I somehow don't see the difficulty with for-loops. Aren't for-loops just glorified while-loops:
for (a; b; c) {
   d
}
--->
{
a;
while (b) {
   d
   c;
}
}

**Comment by openorclose** [comment]
For loops and while loops have major differences:

```javascript
function testFor(){
      let z = [];
      for (let x = 0; x < 10; x = x + 1) {
        z[x] = () => x;
      }
      return z[5](); // should return 5
}
testFor();
```

```javascript
function testWhile(){
      let z = [];      
      //Incorrectly translated for (let x = 0; x < 10; x = x + 1) {
      let x = 0;
      while(x < 10) {
        z[x] = () => x;
        x = x + 1;
      }
      return z[5](); // should return 10
}
testWhile();
```

In the while loop, when ```z[5]``` is called, it will look for the closest ```x```, but the closest ```x``` is in the ```testWhile``` function scope since no ```x``` was declared in the while loop, and at that point in time the value of ```x``` will be 10. So ```z[0]``` through ```z[9]``` should give 10 when called. Furthermore, variable ```x``` is accessible outside the while loop but is inaccessible (except via closures) outside the for loop.

To properly translate the for loop into a while loop according to es2015, it would look like this:

```javascript
function testWhile(){
      let z = [];
      { //for loop scoping
        let x = 0; //initialiser part of for
        while (x < 10) { // update part of for
          let _x = x; // Create a copy of x to be used in the loop body
          
         { // begin loop body scope
              z[_x] = () => _x;
              // _x = _x + 1; (If _x had been updated here the original x will be updated as well!)
          } // end loop body scope

          x = _x; //Replace the original x with the copied version
          x = x + 1; // update part of for 
        }
      } //end for loop scope
      return z[5](); // should return 5
}
testWhile();
```

Of course, it would be possible to do something similar to ```let x = x;``` in the interpreter, and the makeshift ```_x``` would not be used.

**Comment by martin-henz** [comment]
Hi @openorclose :

Yes, I hadn't understood the issue. Yuchuan and I discussed in the meantime. I agree with your explanation. I'm a bit torn in this case.

Deviating from JavaScript is very bad for us: We cannot claim any longer that Source is a strict sub-language of JavaScript.

I understand the proper translation that you are giving, from "for" to "while". However, it seems to be a tad too complicated and asking for more explanation: What if there is already a _x? What if there is another "let x" deep inside the body, perhaps inside a function declaration? I'm afraid our weaker students will get overwhelmed by all of this.

So in this case, I'm sacrificing consistency with JavaScript for an easy explanation for our freshmen. We (tentatively) decided to translate 
for (a; b; c) { d }
to
{ a; while(b) { d c; }
in Source 2018, and thereby make Source 2018 differ from ES2015 in this respect.

But I'd appreciate your honest opinion on this.

**Comment by openorclose** [comment]
@martin-henz  Updated comment with a more in depth explanation of my proposal.

**Comment by martin-henz** [comment]
I like this. There is a slight issue in that we so far don't allow declaration without initialization. 

We could introduce it, of course, which would mean we have:

statement ::= let x [ = expression ];              (with "= undefined" as the default)

The syntactic difference with const is easily explained: "const x;" doesn't make sense!

I suppose that's ok, and would still allow for a programming pattern regarding for-loops to develop. It's a bit unconventional, compared to for-loops in other languages, where the loop variable is being declared after the keyword "for".

However, the BIG advantage is its consistency with the ES2015 as well as with the simple for-to-while translation.

Yu Chuan: what do you think?

-martin

**Comment by martin-henz** [comment]
Yuchuan and I talked a bit more. It is unconventional to not allow a declaration in the initialisation part of the for-loop. We are considering the following specification:

while ( expression ) { statement }
=>
function _body() { statement }
_while( () => expression, _body );

with 
function _while( test, body) {
    if (test()) { body(); _while( test, body); } else { undefined; }
}

for ( assignment1; expression; assignment2 ) { statement }
=>
  assignment1
  while (expression) {
    statement
    assignment2
  }

for ( let x = expression1; expression2; x = expression3 ) { statement }
=>
{
  let _x = expression1;
  function _test(x) {
    return expression2;
  }
  while (_test(_x)) {
    const x = _x;
    statement
    _x = expression3;
  }
}

Consequences:

(1) The semantics is consistent with JavaScript except that all loops evaluate to undefined. This is a trivial difference that only shows up at the lop-level when looking at the REPL printout of toplevel loops.
(2) The designated loop variable (declared with "for (let x =...;...;...) {...}") cannot be assigned to in the body, enforcing good practice.
(3) We don't support "for ( ; ; )". Use "while (true)".

Any comments super welcome!

**Comment by openorclose** [comment]
Can I take it that the above is how loops are going to be explained in class? 

**While-loops**
How are `break` and `continue` going to be expressed with this function expansion? 

**Simple for-loops (no declaration)**
Simple translation into while. BUT

Which expression in ```for (a; b; c){}``` is allowed to be left out in Source? From (3), an empty for statement is not allowed. What about ```for (; b; c){}``` or ```for (a; ; c){}```?

Because in Javascript, if ```b``` is left blank, the test will always evaluate to true and this quirk is not captured in the expansion to a while loop, so the simple while expansion is incorrect. 

Unfortunately, I can't think of any way to express the lack of an expression in valid Source/Javascript:

```javascript
for ( assignment1; expression; assignment2 ) { statement }
=>
assignment1;
while (expression || (/*expression is left empty?*/)) {
  statement
  assignment2;
}
```

Except maybe with another overloaded definition for a for loop with the middle expression blank:

```javascript
for ( assignment1 ; ; assignment2 ) { statement }
=>
assignment1;
while (true) {
  statement
  assignment2;
}
```

Coupled with the next definition of a for loop (with declaration), would 3 different behaviours from a single for statement be too confusing for students?

**For loop with declaration**
```javascript
for ( let x = expression1; expression2; x = expression3 ) { statement }
=>
{
  let _x = expression1;
  while ( (x => expression2)(_x) ) {
    const x = _x;
    statement
    _x = expression3;
  }
}
```

This does look confusing, and any other way of expansion would probably be as well. What if `continue` is called? Does `_x = expression3` still execute?

Perhaps the for loop with declaration could be built upon the previous for loop definition instead going back all the way to while? So students can first learn the while loop, then the 2 (if empty middle expression is allowed) for loops without declaration and finally the for loop with declaration: 

```javascript
for ( let x = a; b; x = c ) { statement ;}
=>
{
  let x;
  for (x = a; b, x = c) {
    const copy_of_x = x;
    {
      const x = copy_of_x;
      statement;
    }
  }
}
```

**Comment by martin-henz** [comment]
**Can I take it that the above is how loops are going to be explained in class?**

Yes, of course. We are teaching here :-)

**Which expression in for (a; b; c){} is allowed to be left out in Source? From (3), an empty for statement is not allowed. What about for (; b; c){} or for (a; ; c){}?**

None of a, b, c are optional. the two given forms of "for" loops are the only ones allowed. Not much loss, I feel, and we are gaining simplicity of explanation/specification/implementation.

**What if continue is called? Does _x = expression3 still execute?**

We will explain "break" and "continue" informally. ("continue" is easy, in this model: It is an abbreviation for "return undefined;". "break" is harder, and left as an exercise for the reader, or as a Quest for the students, when we get to the meta-circular interpreter.)

```
for ( let x = a; b; x = c ) { statement ;}
=>
{
  let x;
  for (x = a; b, x = c) {
    const copy_of_x = x;
    {
      const x = copy_of_x;
      statement;
    }
  }
}
```
Yes, that's very nice. Thanks. We probably don't to allow declaration without initialization, so we might go for this slightly uglier version:

```
for ( let x = a; b; x = c ) { statement ;}
=>
{
  let x = a;
  for (x = x; b, x = c) {
    const  _copy_of_x = x;
    {
      const x = _copy_of_x;
      statement;
    }
  }
}
```

**Comment by martin-henz** [comment]
For clarity, here are the updated specs:

### while-loops

```
while ( expression ) { statement }
=>
function _body() { statement }
_while( () => expression, _body );
```

with

```
function _while( test, body) {
    if (test()) { body(); _while( test, body); } else { undefined; }
}
```

### Simple for-loops

```
for ( assignment1; expression; assignment2 ) { statement }
=>
assignment1;
while (expression) {
    statement
    assignment2;
}
```

### for-loops with declared loop variable

```
for ( let x = expression1; expression2; x = expression3 ) { statement }
=>
{
  let x = expression1;
  for (x = x; expression2, x = expression3) {
    const  _copy_of_x = x;
    {
      const x = _copy_of_x;
      statement;
    }
  }
}
```

Consequences:

(1) The semantics is consistent with JavaScript except that all loops evaluate to undefined. This is a trivial difference that only shows up at the lop-level when looking at the REPL printout of toplevel loops.
(2) The declared loop variable cannot be assigned to in the body, enforcing good practice.
(3) We don't support optional components in the header of for-loops. So for example, for (;;) {...} is not allowed.
(4) "return" is not allowed in the body of loops, enforcing good practice.
(5) We explain **`continue`** and **`break`** informally in class, and use them as exercises in the meta-circular interpreter.

**Comment by martin-henz** [comment]
Hey @openorclose : Do you see @yyc 's pull request
https://github.com/source-academy/js-slang/pull/68
?
Reviewer @remo5000 is not confident to review this pull request, but trusts your judgment. Would you care to comment on the pull request?

**Comment by openorclose** [comment]
@martin-henz 

Referencing (4), where return is not allowed in loops. `test` still returns true when called.

```javascript
  function test(){
      for (let x = 0; x < 2; x = x + 1) {
        return true;
      }
      return false;
  }
  test();
```

**Comment by martin-henz** [comment]
Regarding

**And for consequence (2), a point to consider is that in the for statement without declaration and while statement it is still possible to assign to a loop variable. How is this going to be explained to students?**

The explanation will be: The simple for loop doesn't care what variables are assigned to in the two assignment statements. There isn't any "declared loop variable" in that case. Any "let" variable can be assigned to anywhere in its scope. The exception to this is only "declared loop variables" of for-loops, which can be assigned to only in the update assignment in the loop header.
