### ISSUE TITLE
SVML compiler miscompiles nested for loops

### ISSUE THREAD

**Issue by angelsl** [source-academy/js-slang#669]
The following snippet produces the wrong result when run on both the Source §3 Concurrent VM and the Sinter VM:

```js
for (let j = 0; j < 10; j = j + 1) {
    for (let i = 0; i < 1000; i = i + 1) {}
    display(j);
}
```

so I assume it is a miscompilation.

**Comment by martin-henz** [comment]
To narrow down the problem: This works properly:
```
let j = 0;
for ( j = 0; j < 10; j = j + 1) {
    let i = 0;
    for ( i = 0; i < 1000; i = i + 1) {}
    display(j);
}
```
This means the culprit is likely the implementation of the special treatment of loop control variables, see page 4 in https://source-academy.github.io/source/source_3_concurrent.pdf

**Comment by angelsl** [comment]
That is probably the case—I ran the program in the [Sinter VM](https://angelsl.github.io/sinter/) with assertions enabled and it complained of an uninitialised load.

Here is the compilation of this program:

```js
// same program as issue minus the display
for (let i = 0; i < 10; i = i + 1) {
  for (let j = 0; j < 10; j = j + 1) {}
}
```

```
Entry function: 0
#0:
Stack Size: 3
Env Size: 1
Num Args: 0
0: LGCI   0
1: STLG   0
2: LGCU  
3: POPG  
4: LDLG   0
5: LGCI   10
6: LTG   
7: BRF    47
8: NEWENV 3
9: LDLG   2
10: STLG   0
11: LGCU  
12: POPG  
13: LDLG   0
14: STLG   1
15: LGCU  
16: POPG  
17: LGCI   0
18: STLG   2
19: LGCU  
20: POPG  
21: LDLG   2
22: LGCI   10
23: LTG   
24: BRF    20
25: NEWENV 2
26: LDPG   2 1
27: STLG   0
28: LGCU  
29: POPG  
30: LDLG   0
31: STLG   1
32: LGCU  
33: POPG  
34: LGCU  
35: POPG  
36: LDPG   2 1
37: LGCI   1
38: ADDG  
39: STPG   2 1
40: LGCU  
41: POPG  
42: POPENV
43: BR     -22
44: LGCU  
45: POPG  
46: LDLG   2
47: LGCI   1
48: ADDG  
49: STLG   2
50: LGCU  
51: POPG  
52: POPENV
53: BR     -49
54: LGCU  
55: LGCU  
56: RETG  
```

The crash is on the ldl.g at index 9 which comes immediately after a newenv, which is clearly wrong since the current environment would be filled with uninitialised entries. It should probably be an ldp.g (to load from a parent of the current environment).

Will investigate further soon.
