### ISSUE TITLE
"yarn build" Command Fails

### ISSUE THREAD

**Issue by sarahgoh97** [source-academy/js-slang#691]
Hello, I am trying to build js-slang but it keeps returning an error code. "yarn" works but "yarn build" does not. When I try running the command in js-slang, it gives me this message:

```
$ yarn build
yarn run v1.22.4
$ yarn docs && yarn tsc
$ yarn jsdoc && yarn autocomplete
$ ./scripts/jsdoc.sh
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I have been running these commands on Git Bash since I am using a Windows laptop. Is there anything I am missing or doing wrong? Thank you!

**Comment by angelsl** [comment]
Could you try developing in [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/install-win10)? Unfortunately the build process does not work on Windows currently :(

**Comment by angelsl** [comment]
Alternatively, you could skip the docs build and just run `yarn run tsc`.

**Comment by sarahgoh97** [comment]
yarn run tsc doesn't seem to work either:

$ yarn run tsc                                                                                                                                                                                       yarn run v1.22.4                                                                                                                                                                                     $ C:\Users\sarah\source\repos\js-slang\node_modules\.bin\tsc                                                                                                                                         src/editors/ace/docTooltip/index.ts:1:26 - error TS2307: Cannot find module './External libraries.json' or its corresponding type declarations.                                                                                                                                                                                                                                                           1 import * as ext_lib from './External libraries.json'                                                                                                                                                                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                    src/editors/ace/docTooltip/index.ts:2:27 - error TS2307: Cannot find module './source_1.json' or its corresponding type declarations.                                                                                                                                                                                                                                                                     2 import * as source_1 from './source_1.json'                                                                                                                                                                                    ~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                             src/editors/ace/docTooltip/index.ts:3:27 - error TS2307: Cannot find module './source_2.json' or its corresponding type declarations.                                                                                                                                                                                                                                                                     3 import * as source_2 from './source_2.json'                                                                                                                                                                                    ~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                             src/editors/ace/docTooltip/index.ts:4:27 - error TS2307: Cannot find module './source_3.json' or its corresponding type declarations.                                                                                                                                                                                                                                                                     4 import * as source_3 from './source_3.json'                                                                                                                                                                                    ~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                             src/editors/ace/docTooltip/index.ts:5:38 - error TS2307: Cannot find module './source_3_concurrent.json' or its corresponding type declarations.                                                                                                                                                                                                                                                          5 import * as source_3_concurrent from './source_3_concurrent.json'                                                                                                                                                                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                       src/editors/ace/docTooltip/index.ts:6:35 - error TS2307: Cannot find module './source_3_non-det.json' or its corresponding type declarations.                                                                                                                                                                                                                                                             6 import * as source_3_non_det from './source_3_non-det.json'                                                                                                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                             src/editors/ace/docTooltip/index.ts:7:27 - error TS2307: Cannot find module './source_4.json' or its corresponding type declarations.                                                                                                                                                                                                                                                                     7 import * as source_4 from './source_4.json'                                                                                                                                                                                    ~~~~~~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Found 7 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by angelsl** [comment]
Oh, my bad then, I guess the build needs the documentation to be generated now :/

You can try WSL; it should work.
