### ISSUE TITLE
Block statements not documented in Source §3 doc

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#72]
It seems that we are allowing block statements 

statement ::= block-statement

block-statement ::= { statement }

This is currently not documented in the Source §3 doc. @yyc : Is this implemented? Should I add it? Is this a general feature of Source now? In this case, I should update all docs Source §1-4.

**Comment by yyc** [comment]
Block statements are a necessary part of for/while/if statements (or at least how estree parses them) so yes, we are implicitly allowing them. That said, I'm not sure standalone block statements should be encouraged (could be left as a discouraged undocumented feature). I'll look into seeing if we can disable standalone block statements (i.e. those not attached to if/else/for/while).

**Comment by martin-henz** [comment]
We should not disable standalone block statements. We use them to explain the semantics of for loops with declared loop variables.

We will not encourage standalone block statements.

**Comment by yyc** [comment]
....ah.
I suppose this is a more breaking bug than being able to define shadowed
variables in for loop blocks.

**Comment by openorclose** [comment]
@yyc, I noticed another problem with shifting the block scope creation as well, in that it would allow arguments in a function declaration to be redeclared.

**Comment by martin-henz** [comment]
done
