### ISSUE TITLE
Operators === and !== for Source §3+ should check that the two arguments are of the same type

### ISSUE THREAD

**Issue by btzy** [source-academy/js-slang#734]
It seems that it was intended (as per #389) that operators === and !== for Source §3+ check that the two arguments are of the same type.  So the issue raised at https://github.com/source-academy/cadet-frontend/issues/1451 should not have worked in Source §3+ either.

In addition, the specs for Source §3+ are not clear whether the LHS 'any' and RHS 'any' must be of the same type - this should be fixed too.

**Comment by martin-henz** [comment]
The specs are clear on this: Any is any. Insisting on the same type would make the specs more complicated.

There is no checking for same argument type for === and !== in Source §3. The environment model can explain pointer equality. We don't need to specify what kind of thing the pointers point to.

**Comment by btzy** [comment]
Hmm, then it seems that I misinterpreted your comment on #389.
