### ISSUE TITLE
JSON.stringify in Source §4

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#74]
The syntax stands out: we have no other library that gets accessed with "dot" in 2018.

How about calling it json_stringify?

As documentation, we refer to an appropriate online document.

**Comment by thomastanck** [comment]
I believe this is resolved by #23, the builtin `JSON.stringify` is now exposed as `stringify`.

**Comment by martin-henz** [comment]
New specs have stringify removed.
