### ISSUE TITLE
Stepper: Redeclaration of predeclared functions

### ISSUE THREAD

**Issue by zhaojj2209** [source-academy/js-slang#772]
The stepper currently does not deal with redeclaration of predeclared functions properly. If the student declares a function with the same name as a predeclared function, the stepper will continue to use the Source predeclared function in its evaluation.

**Comment by martin-henz** [comment]
can't reproduce this bug. Is it fixed?

**Comment by martin-henz** [comment]
I'm trying:

const math_cos =  x => x;
math_cos(0);

and the stepper works as expected, with output 0.

**Comment by zhaojj2209** [comment]
The bug occurs when trying to redeclare source 2 list functions, like so:

```
const reverse = x => x;
reverse(0);
```

**Comment by martin-henz** [comment]
Oh, that's weird. Thanks for pointing this out @zhaojj2209 
Any idea how to fix this?
