### ISSUE TITLE
Optimise RTTC for logical binary operators to follow ES6

### ISSUE THREAD

**Issue by ningyuansg** [source-academy/js-slang#78]
https://www.ecma-international.org/ecma-262/6.0/#sec-binary-logical-operators-runtime-semantics-evaluation

> 1. LogicalORExpression : LogicalORExpression || LogicalANDExpression
> 2. Let lref be the result of evaluating LogicalORExpression.
> 3. Let lval be GetValue(lref).
> 4. Let lbool be ToBoolean(lval).
> 5. ReturnIfAbrupt(lbool).
> 6. If lbool is true, return lval.
> 7. Let rref be the result of evaluating LogicalANDExpression.
> 8. Return GetValue(rref).

The RTTC check on rref creates a recursive process.

**Comment by openorclose** [comment]
Should we close this now that logical expressions are now converted into conditionals?

**Comment by thomastanck** [comment]
Yes
