### ISSUE TITLE
No "if" statement in S3.

### ISSUE THREAD

**Issue by imsamuel** [source-academy/js-slang#793]
I'm curious for the reason on why S3 does not have an "if" statement. Attempting to use an "if" by itself results in an error. 

```shell
Missing "else" in "if-else" statement.
```

**Comment by martin-henz** [comment]
If statements without else would require introduction of an extra rule in the documentation, a mention in the textbook to explain it and effort in the implementation of Source. We left it out to keep things simple. You can easily write conditional statements with an empty alternative statement:

`if (my_predicate) { here goes the consequent statement } else { }`

**Comment by imsamuel** [comment]
I see, the reasons make sense! Thanks for the suggestion.
