### ISSUE TITLE
Incorrect acorn-walk imports and typings

### ISSUE THREAD

**Issue by angelsl** [source-academy/js-slang#800]
Currently we import from `acorn-walk` using this strange subpath:

https://github.com/source-academy/js-slang/blob/5fcf62d0536cf48beff155b34d44cba5e1b9859e/src/index.ts#L1

and we also provide our own typings for `acorn-walk` in [src/typings/acorn-walk.d.ts](https://github.com/source-academy/js-slang/blob/master/src/typings/acorn-walk.d.ts).

acorn-walk v8.0 added an `exports` directive to their `package.json` which is read by Node's import handling mechanism, and this causes our `import 'acorn-walk/dist/walk'` to fail. Somehow this passed all our tests and CI when I updated dependencies a month ago (#785) and no one has noticed this because it seems few people run js-slang under Node.js directly. But trying to do so now will result in this error:

```
$ node dist/index.js
node:internal/modules/cjs/loader:462
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/walk' is not defined by "exports" in .../js-slang/node_modules/acorn-walk/package.json
...
    at Object.<anonymous> (.../js-slang/dist/index.js:13:16) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

I only noticed this when trying to update js-slang in the autograder (due to the changes to `parse`). I've worked around the issue for now, but we should fix this issue in js-slang:

- Remove our own `acorn-walk` typings, and use those provided by the package. Fix any type errors that result (acorn uses `acorn.Node` instead of `estree.Node` in its function parameters, and the former has a few properties not in `estree.Node`)
- Change the imports to use the "supported" imports i.e. just `import 'acorn-walk'`.

We also have one instance of `import 'acorn/dist/acorn'`, but as that is done in a test file, it is handled by Jest's import resolution mechanism, so we don't run into any issue yet. But we should also fix this.

I will handle this in the winter break. JavaScript packaging is such a mess...

**Comment by martin-henz** [comment]
Yes, I noticed this because my SICP JS test suite doesnt run any longer, after upgrading js-slang to 0.4.69.

**Comment by martin-henz** [comment]
Would be great if we could get it to run by mid december. Target for the SICP JS print edition is 31/12.

**Comment by angelsl** [comment]
Oh, in that case I will get to it sooner. Reading week, if I have time.
