### ISSUE TITLE
 Migrate from travis-ci.org

### ISSUE THREAD

**Issue by zhengqunkoo** [source-academy/js-slang#811]
Travis CI announced in an email https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom that CI management will be under travis-ci.com by the end of this year.

We could still stick with Travis CI, but rOpenSci advocates migrating from Travis CI altogether https://ropensci.org/technotes/2020/11/19/moving-away-travis/. GitHub Actions looks promising.

**Comment by zhengqunkoo** [comment]
Of course, all other repositories @source-academy has on travis-ci.com should also be migrated from travis-ci.com.

**Comment by openorclose** [comment]
We're already using github actions alongside travis, I guess there shouldn't be an issue simply removing travis
