### ISSUE TITLE
Stepper: Renaming for BlockStatements occur before substitution

### ISSUE THREAD

**Issue by Zacchua** [source-academy/js-slang#872]
Capture Avoiding Substitution is implemented in blocks by renaming variables when an expression to be substituted into the block has a free variable with the same name. However the renaming occurs in the first step of the substitution, instead of at the step where substitution occurs
<img width="248" alt="Screenshot 2021-02-17 at 4 41 58 PM" src="https://user-images.githubusercontent.com/57891439/108178587-9022a500-713f-11eb-830b-c44ac59ee785.png">

in the above case constant "z" in function f is renamed to "z (const)" as z occurs free in the body of g, and g is called in f, and the body of g is hence substituted into f.

**Comment by martin-henz** [comment]
The renaming **appears** to occur before the substitution. It **actually** occurs after the substitution, but it destructively changes the syntax tree node and thus affects earlier steps.
