### ISSUE TITLE
Stepper: Incorrect result

### ISSUE THREAD

**Issue by Zacchua** [source-academy/js-slang#874]
Stepper gives an incorrect result of "g();" instead of "1;" in the following function 

<img width="180" alt="Screenshot 2021-02-17 at 5 56 41 PM" src="https://user-images.githubusercontent.com/57891439/108187935-f6142a00-7149-11eb-8794-467f5f984e40.png">

<img width="1257" alt="Screenshot 2021-02-17 at 5 39 02 PM" src="https://user-images.githubusercontent.com/57891439/108185467-4a69da80-7147-11eb-8b54-c0b69e0b93d9.png">

**Comment by martin-henz** [comment]
https://share.sourceacademy.nus.edu.sg/4iq37

**Comment by thomastanck** [comment]
https://share.sourceacademy.nus.edu.sg/37b2s
