### ISSUE TITLE
Unintended behavior involving self-defined functions and pairs

### ISSUE THREAD

**Issue by Wingedevil** [source-academy/js-slang#88]
```
function s() {
    return 1;
}
head(pair(s, s)) === s;
```
We expect this equality to be true, but unfortunately, it resolves to false;

**Comment by openorclose** [comment]
This is due to a more general bug, where Source-defined functions are not passed into native Javascript functions properly, and while calling the functions give the same value, they do not refer to the same object.

**Comment by thomastanck** [comment]
Resolved by #92 :tada:
