### ISSUE TITLE
Fail to check reassignment of predefined const symbols

### ISSUE THREAD

**Issue by LuminousXLB** [source-academy/js-slang#892]
![image](https://user-images.githubusercontent.com/23524048/109992831-9ec7a980-7d46-11eb-9e67-519086df67f9.png)

![image](https://user-images.githubusercontent.com/23524048/109992944-bef76880-7d46-11eb-91b4-1d090733e951.png)

**Comment by martin-henz** [comment]
This issue is unclear: What language version? Source §1,2,3,4?

What is the observed behaviour? What is in your view the expected behaviour? What is the justification for your expectation?

**Comment by LuminousXLB** [comment]
## What language version? Source §1,2,3,4?

I'm using Source §4. 
But this issue should apply to any version designed to reject redeclaration or reassignment of constant symbols.

## What is the observed behaviour?

I can successfully redeclare predefined symbols, as shown in the screenshots, which change these symbols' value.

## What is the expected behaviour?

The redeclaration of the predefined constant symbols should be rejected.

## What is the justification for your expectation?

Constant variables' value should not be modified. 
But allowing to redeclare these symbols makes it possible to change the value of constant variables.

**Comment by martin-henz** [comment]
I think there is a misunderstanding. User programs are free to redeclare predeclared names. This is the case in JavaScript and in Source. 

See SICP JS for an explanation: https://source-academy.github.io/sicp/chapters/3.2.4.html#p2
Basically: the user program should be seen as included in an implicit block.

In general, redeclaration of names in nested blocks is allowed. { const x = 1; { const x = 2; ... } } is fine.
