### ISSUE TITLE
Error message for incorrect array index

### ISSUE THREAD

**Issue by raivatshah** [source-academy/js-slang#896]
The current error message for an incorrect array index is `"Expected array index as prop, got other number"`. 

I checked the criteria (under the `isArrayIndex` function) for raising this error and it seems that the error is thrown whenever the index is either negative or larger than the maximum integer size. If that is indeed the criteria (please correct me if I'm wrong), then I think that a better error message, with some indication of this criteria, might be better than `"other number"` (which I think might be vague).

**Comment by martin-henz** [comment]
The error message is consistent with page 6 of https://source-academy.github.io/source/source_3.pdf:

In array access arr[key], only arrays are allowed as arr and only integers are allowed as key.
Array indices in Source are limited to integers i in the range 0 ≤ i < 2^(32 − 1).

**Comment by raivatshah** [comment]
Alright, thanks for pointing it out!
