### ISSUE TITLE
Minor bug regarding `this` in objects

### ISSUE THREAD

**Issue by openorclose** [source-academy/js-slang#93]
```javascript
function t() {
    return this.x ;
}
const o = {x: 1234, y: t};
o.y();
```
should give 1234, but gives `undefined` instead.

`this` is not in the source specs, however, so not a high priority.

**Comment by martin-henz** [comment]
We used to teach object-oriented programming in CS1101S, until 2017. This year, moving to a larger batch and making it a requirement for CS, we decided to take it out and focus on the environment model. We introduce literal, JSON-style objects, and treat them roughly like we treat arrays: Just another kind of built-in data structure.

So 
this 
and
o.y()
are not part of Source §x. This is also consistent with the textbook which does not have this kind of OOP. 

How to remove these things properly from Source §x is another matter. Maybe we should just dis-allow the use of the name "this" for variables and constants.

As you know, the syntax
o.y()
is different from
(o.y)()
The former is "message sending" and sets "this" in the method, whereas the latter just retrieves a function from o and calls it (with "this" being "undefined"). 

To avoid confusion, we should dis-allow the syntax
o.y()

**Comment by martin-henz** [comment]
Source §2 properly dis-allows this and o.y(). We can just glean from there how to do it in Source §3 and §4.

**Comment by martin-henz** [comment]
Yes, this is a keyword, and not supported by Source §x. So this is a simple syntax error.

**Comment by thomastanck** [comment]
Closing in favour of #129, a combination of a bunch of issues, to clean up the list of issues a little.
