### ISSUE TITLE
Ace: ECMAScript top-level names (not keywords) are syntax-highlighted when they shouldn't be

### ISSUE THREAD

**Issue by btzy** [source-academy/js-slang#934]
"Array" is highlighted differently in the editor, even though it is not a Source keyword or builtin.  Note that it is also not a ECMAScript keyword, and so users are allowed to declare a new variable called "Array".

![image](https://user-images.githubusercontent.com/6948096/114436109-8c6b4600-9bf7-11eb-830f-b18090e6f8bb.png)

Presumably this is the offending code:

https://github.com/source-academy/js-slang/blame/8ba65fd4a78bf06cd43c28403f5b0a2b4f1d027a/src/editors/ace/modes/source.ts#L118-L133

**Comment by martin-henz** [comment]
The problem lies here: js-slang/src/editors/ace/modes/source.ts
