### ISSUE TITLE
REPL: Shift-Enter does not work

### ISSUE THREAD

**Issue by btzy** [source-academy/js-slang#936]
The tooltip suggests that Shift-Enter will evaluate the things in the REPL box, but instead nothing happens.  Tried on Chrome 89.

![image](https://user-images.githubusercontent.com/6948096/114821021-82f9fd80-9df2-11eb-88f0-b7fe28ca699f.png)

**Comment by thomastanck** [comment]
Resolved by https://github.com/source-academy/cadet-frontend/pull/1722.
