### ISSUE TITLE
prompt displays quotes

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#98]
The function prompt in Source currently displays double quotes around the string, whereas JavaScript's prompt (of course) does not display any quotes.

**Comment by jiachen247** [comment]
@thomastanck the `toString` function referenced above is actually important to handle printing of non primative types (eg arrays and objects) without invoking their respective default `toString` methods. 

The fix should actually be done here.

https://github.com/source-academy/js-slang/blob/0c0d033c3b4b0d00879688d5e983be9d5ab2f4be/src/interop.ts#L70-L71

**Comment by thomastanck** [comment]
@jiachen247 you're right. Calling toString to a string "should" simply return the string itself.
![maim](https://user-images.githubusercontent.com/829070/48636789-d50e7d00-ea06-11e8-85d9-d1360d3eb030.png)

Will need to check with how changing this affects source-academy/cadet-frontend's `display` and various other functions.

**Comment by thomastanck** [comment]
@jiachen247 Nice! Want to make a PR? Then you can get a nice <Contributor>
badge 👀

**Comment by thomastanck** [comment]
Resolved by #165
