### ISSUE TITLE
else clause in conditional statements should be optional from Source §3 onwards

### ISSUE THREAD

**Issue by martin-henz** [source-academy/js-slang#993]

**Comment by blackening** [comment]
Reason for proposal: to put good programming habits into students.
In Source §1/2, writing if without else is most likely a missing return value.

In Source §3 and after, the usage of two specific programming patterns leads to empty else blocks.

The first is the guard clause:

```
function f(params) {
     if(exceptional_cond(params)) {
           return something
     }
     // ... rest of program ...
}
```

The other is where something is defined based on an input:

```
function f(params) {
      let x = something;
      if(cond(params)) {
          x = something_else;
      }
      // ... rest of program ...
}
```
There is no need to teach that if-else can simply be written as if statements.
